import Link from "next/link";
import { getLocale } from "@/i18n/server";
import { COMPANY, COOKIE_NOTICE_VERSION } from "@/lib/legal";

export const metadata = { title: "Çerez Politikası · Cookie Policy | Make Art Studio" };

const COPY = {
  tr: { back: "Ana sayfaya dön", title: "Çerez ve Yerel Depolama Politikası", intro: "Sitede reklam veya davranışsal izleme çerezi kullanılmaz. Açıkça talep ettiğiniz işlevler için zorunlu depolama kullanılır; Google Haritalar gibi üçüncü taraf içerik yalnızca seçiminizden sonra yüklenir.", rows: [["lang", "Dil tercihi", "Birinci taraf çerez", "1 yıl", "İşlevsel"], ["Supabase auth", "Güvenli öğrenci/veli oturumu", "Birinci taraf oturum çerezleri", "Oturuma göre", "Kesinlikle gerekli"], ["admin_session", "Admin oturumu", "HttpOnly birinci taraf çerez", "8 saat", "Kesinlikle gerekli"], ["makeart_external_media_2026_07", "Google Haritalar yükleme tercihi", "Tarayıcı localStorage", "Tercih silinene kadar", "İsteğe bağlı"], ["makeart_ai_transfer_consent_2026_07", "Harici AI aktarım tercihi", "Tarayıcı localStorage", "Geri çekilene kadar", "İsteğe bağlı"]], note: "Harici medya tercihinizi İletişim bölümündeki harita alanından geri çekebilirsiniz. AI tercihi sohbet penceresinden geri çekilebilir. Tarayıcı ayarlarından site verilerini silmek de tüm tercihleri sıfırlar." },
  en: { back: "Back to homepage", title: "Cookie and Local Storage Policy", intro: "The site does not use advertising or behavioural-tracking cookies. Essential storage supports features you request; third-party content such as Google Maps loads only after your choice.", rows: [["lang", "Language preference", "First-party cookie", "1 year", "Functional"], ["Supabase auth", "Secure student/parent session", "First-party session cookies", "Session-dependent", "Strictly necessary"], ["admin_session", "Admin session", "HttpOnly first-party cookie", "8 hours", "Strictly necessary"], ["makeart_external_media_2026_07", "Google Maps loading choice", "Browser localStorage", "Until cleared", "Optional"], ["makeart_ai_transfer_consent_2026_07", "External AI transfer choice", "Browser localStorage", "Until withdrawn", "Optional"]], note: "Withdraw external-media permission in the map area of the Contact section and AI permission inside the assistant. Clearing this site's browser data also resets all choices." },
  ru: { back: "На главную", title: "Политика cookies и локального хранилища", intro: "Сайт не использует рекламные или поведенческие cookies. Необходимое хранилище поддерживает запрошенные функции; Google Maps загружается только после вашего выбора.", rows: [["lang", "Выбранный язык", "Собственный cookie", "1 год", "Функциональный"], ["Supabase auth", "Защищённая сессия", "Сессионные cookies", "По сессии", "Необходимый"], ["admin_session", "Сессия администратора", "HttpOnly cookie", "8 часов", "Необходимый"], ["makeart_external_media_2026_07", "Разрешение Google Maps", "localStorage", "До удаления", "Необязательный"], ["makeart_ai_transfer_consent_2026_07", "Выбор внешнего ИИ", "localStorage", "До отзыва", "Необязательный"]], note: "Разрешение карты отзывается в разделе контактов, разрешение ИИ — в окне ассистента. Удаление данных сайта в браузере сбрасывает все варианты." },
} as const;

export default async function CookiesPage() {
  const locale = await getLocale(); const t = COPY[locale] ?? COPY.tr;
  return <main className="min-h-screen bg-[var(--background)] px-4 py-12 text-[var(--foreground)] sm:px-6"><article className="mx-auto max-w-4xl"><Link href="/" className="mb-6 inline-flex text-sm text-[var(--pink-dark)] hover:underline">← {t.back}</Link><div className="rounded-3xl border border-[var(--border)] bg-white p-6 sm:p-9"><h1 className="text-2xl font-bold sm:text-3xl">{t.title}</h1><p className="mt-2 text-xs text-[var(--muted)]">{COMPANY.lastUpdated} · {COOKIE_NOTICE_VERSION}</p><p className="mt-6 text-sm leading-relaxed text-[var(--muted)]">{t.intro}</p><div className="mt-7 overflow-x-auto"><table className="w-full min-w-[680px] border-collapse text-left text-xs"><thead><tr className="border-b border-[var(--border)] text-[var(--foreground)]"><th className="p-3">Name</th><th className="p-3">Purpose</th><th className="p-3">Technology</th><th className="p-3">Duration</th><th className="p-3">Category</th></tr></thead><tbody>{t.rows.map((row) => <tr key={row[0]} className="border-b border-[var(--border)]/70 text-[var(--muted)]">{row.map((cell) => <td key={cell} className="p-3 align-top">{cell}</td>)}</tr>)}</tbody></table></div><p className="mt-6 rounded-2xl bg-[var(--blue-light)]/50 p-4 text-sm leading-relaxed text-[var(--muted)]">{t.note}</p><div className="mt-7 flex gap-4 text-sm"><Link href="/privacy" className="text-[var(--pink-dark)] underline">KVKK</Link><Link href="/terms" className="text-[var(--pink-dark)] underline">Terms</Link></div></div></article></main>;
}
