#!/usr/bin/env node
/**
 * Imports the bundled archive in src/data/gallery.ts into public.gallery_items.
 *
 *   node scripts/import-gallery.mjs
 *
 * Run once after 0024. The rows it writes have no storage_path, which is what
 * marks them as "the pixels live in public/gallery/, served by the Vercel CDN".
 * Nothing is uploaded and nothing is copied — this only teaches the database
 * about photos the site already ships, so the admin can reorder and retitle them
 * alongside anything uploaded later.
 *
 * Re-runnable: `src` is uniquely indexed for bundled rows, so ON CONFLICT keeps
 * whatever the admin has since changed (position, captions, visibility) and only
 * refreshes the derived image fields. Running this twice must never undo a
 * afternoon of curation.
 */

import { readFile } from "node:fs/promises";
import path from "node:path";
import pg from "pg";

async function loadEnv() {
  const raw = await readFile(path.resolve(process.cwd(), ".env.local"), "utf8");
  for (const line of raw.split(/\r?\n/)) {
    const m = line.match(/^([A-Z0-9_]+)\s*=\s*(.*)$/);
    if (!m) continue;
    if (process.env[m[1]] === undefined) {
      process.env[m[1]] = m[2].trim().replace(/^["']|["']$/g, "");
    }
  }
}

/**
 * src/data/gallery.ts is a TypeScript module, and this is a plain node script
 * with no loader. The file is generated by build-gallery.mjs from a fixed
 * template though, so the two array literals can be lifted out directly — which
 * beats adding tsx/esbuild to the toolchain for one read.
 */
async function readManifest() {
  const file = path.resolve(process.cwd(), "src", "data", "gallery.ts");
  const source = await readFile(file, "utf8");

  const extract = (name) => {
    const start = source.indexOf(`export const ${name}`);
    if (start === -1) throw new Error(`${name} not found in ${file}`);
    // Seek past the `=` first. The declaration is
    // `export const galleryPhotos: GalleryPhoto[] = [...]`, so the first `[`
    // after the name belongs to the TYPE annotation — matching on that yields
    // an immediately-closed `[]` and silently imports nothing.
    const eq = source.indexOf("=", start);
    if (eq === -1) throw new Error(`${name} has no initialiser`);
    const open = source.indexOf("[", eq);
    let depth = 0;
    for (let i = open; i < source.length; i++) {
      if (source[i] === "[") depth++;
      else if (source[i] === "]") {
        depth--;
        if (depth === 0) return JSON.parse(source.slice(open, i + 1));
      }
    }
    throw new Error(`unterminated ${name} array`);
  };

  return { categories: extract("galleryCategories"), photos: extract("galleryPhotos") };
}

async function run() {
  await loadEnv();
  if (!process.env.DB_URL) {
    console.error("DB_URL is not set in .env.local");
    process.exit(1);
  }

  const { categories, photos } = await readManifest();
  console.log(`manifest: ${photos.length} photos across ${categories.length} categories`);

  const client = new pg.Client({
    connectionString: process.env.DB_URL,
    ssl: { rejectUnauthorized: false },
  });
  await client.connect();

  try {
    await client.query("BEGIN");

    // Position is assigned per category in manifest order, which is the order
    // the site renders today. Importing must not visibly change the gallery.
    const seen = new Map();
    let inserted = 0;
    let refreshed = 0;

    for (const p of photos) {
      const position = (seen.get(p.category) ?? 0) + 1;
      seen.set(p.category, position);

      const res = await client.query(
        `INSERT INTO public.gallery_items
           (kind, category, "group", src, thumb, blur, width, height, position)
         VALUES ('photo', $1, $2, $3, $4, $5, $6, $7, $8)
         ON CONFLICT (src) WHERE storage_path IS NULL DO UPDATE SET
           thumb  = EXCLUDED.thumb,
           blur   = EXCLUDED.blur,
           width  = EXCLUDED.width,
           height = EXCLUDED.height
         RETURNING (xmax = 0) AS is_insert`,
        [p.category, p.group, p.src, p.thumb, p.blur, p.width, p.height, position],
      );

      res.rows[0].is_insert ? inserted++ : refreshed++;
    }

    await client.query("COMMIT");
    console.log(`✓ ${inserted} imported, ${refreshed} already present (left untouched)`);

    const { rows } = await client.query(
      `SELECT category, count(*)::int AS n, count(*) FILTER (WHERE visible)::int AS shown
         FROM public.gallery_items GROUP BY category ORDER BY category`,
    );
    for (const r of rows) console.log(`  ${r.category.padEnd(12)} ${r.n} items (${r.shown} visible)`);
  } catch (err) {
    await client.query("ROLLBACK").catch(() => {});
    console.error("✗ rolled back:", err.message);
    process.exitCode = 1;
  } finally {
    await client.end();
  }
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
