// AUTO-GENERATED by scripts/build-gallery.mjs — do not edit by hand.
// Re-run: node scripts/build-gallery.mjs

export type GalleryLocale = "tr" | "en" | "ru";

export interface GalleryPhoto {
  /** Full-size WebP for the lightbox. */
  src: string;
  /** Smaller WebP for the masonry grid. */
  thumb: string;
  width: number;
  height: number;
  /** Inline 16px placeholder, avoids a network round-trip before first paint. */
  blur: string;
  category: string;
  group: string | null;
}

export interface GalleryGroup {
  slug: string;
  label: Record<GalleryLocale, string>;
}

export interface GalleryCategory {
  slug: string;
  label: Record<GalleryLocale, string>;
  groups: GalleryGroup[];
  count: number;
}

export const galleryCategories: GalleryCategory[] = [
  {
    "slug": "lessons",
    "label": {
      "tr": "Yaratıcılık Dersleri",
      "en": "Creative Lessons",
      "ru": "Творческие занятия"
    },
    "groups": [
      {
        "slug": "junior",
        "label": {
          "tr": "4–6 yaş",
          "en": "Ages 4–6",
          "ru": "4–6 лет"
        }
      },
      {
        "slug": "middle",
        "label": {
          "tr": "7–9 yaş",
          "en": "Ages 7–9",
          "ru": "7–9 лет"
        }
      },
      {
        "slug": "senior",
        "label": {
          "tr": "10+ ve yetişkinler",
          "en": "Ages 10+ & adults",
          "ru": "10+ и взрослые"
        }
      }
    ],
    "count": 71
  },
  {
    "slug": "camp",
    "label": {
      "tr": "Sanat Kampı",
      "en": "Summer Art Camp",
      "ru": "Летний арт-лагерь"
    },
    "groups": [
      {
        "slug": "summer-2026",
        "label": {
          "tr": "2026 Yaz",
          "en": "Summer 2026",
          "ru": "Лето 2026"
        }
      }
    ],
    "count": 40
  },
  {
    "slug": "individual",
    "label": {
      "tr": "Birebir Atölye",
      "en": "One-to-One Studio",
      "ru": "Индивидуально"
    },
    "groups": [],
    "count": 17
  },
  {
    "slug": "workshops",
    "label": {
      "tr": "Usta Atölyeleri",
      "en": "Master Classes",
      "ru": "Мастер-классы"
    },
    "groups": [
      {
        "slug": "kids",
        "label": {
          "tr": "Çocuklar için",
          "en": "For children",
          "ru": "Для детей"
        }
      },
      {
        "slug": "adults",
        "label": {
          "tr": "Yetişkinler için",
          "en": "For adults",
          "ru": "Для взрослых"
        }
      }
    ],
    "count": 32
  }
];

export const galleryPhotos: GalleryPhoto[] = [
  {
    "src": "/gallery/lessons/junior/junior-001.webp",
    "thumb": "/gallery/lessons/junior/junior-001-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRsoAAABXRUJQVlA4IL4AAADQBACdASoQABwAPu1iqk2ppaQiMAgBMB2JbACdMoEUVleB7pSo0BEOHeJJiRrUAAD1wTduaXGyqdDCqb0UWem7XSiYL+M4rTwlemewBSmZVvBhbpikDQhJtKAAfvPt8E52JhH8EvvbbDgzA8dap1PiCh7hyLb47dXRE70AL0I6BCkAQSwJCSkkjEpY90/I7BgaovA18rBkJMgQVp59Y6QaejPy59MbVChyJzrIggAtKnvA2HkKUMEh+Eb/4AAA",
    "category": "lessons",
    "group": "junior"
  },
  {
    "src": "/gallery/lessons/junior/junior-002.webp",
    "thumb": "/gallery/lessons/junior/junior-002-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRsYAAABXRUJQVlA4ILoAAAAwBACdASoQABwAPu1iqU2ppaOiMAgBMB2JbACdMoMYA0hhgZOPm545pIAA/sp6h+7XCj1BViYpR0n6xrcEuPjRM86TOiapSi86ZiEwBdxnmkErlytqttQ2Qj0xa6oL37gujJieAC0Mb6GRl5mNRN4zBZPnuuBB5JTgxDubsxT3z7oDppfv1tant/lphKPC940B+QxT9URxjXlvGKgq8cwUMV5O26SlDfpfq+m/z+AGGnMiedDGHlQAAAA=",
    "category": "lessons",
    "group": "junior"
  },
  {
    "src": "/gallery/lessons/junior/junior-003.webp",
    "thumb": "/gallery/lessons/junior/junior-003-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRsQAAABXRUJQVlA4ILgAAABwBACdASoQABwAPu1iqU2ppaOiMAgBMB2JbACdL1A4QMYxVl0+V+iNkv7SAAD+6sk57q8zjgIxF5s8lTluJJOTgeWVBd4IAYBXn87/vXaSS+8jPlicw8hhImADi3VBGsFvyPdUm+o6yWQ27VITv7NlGenld9rWYyhUGfI80lJnX6qe95ESLCVPgX6zsiaU8KPbkwUYqtJ35XzNkNFa6D914WqqiEISgjnFMV0bPd7HHaN/Vu0U5IAA",
    "category": "lessons",
    "group": "junior"
  },
  {
    "src": "/gallery/lessons/junior/junior-004.webp",
    "thumb": "/gallery/lessons/junior/junior-004-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRsQAAABXRUJQVlA4ILgAAACQBACdASoQABwAPu1iqU2ppaOiMAgBMB2JagCdMoMgg0iw7MxdsEZ8eW6QxgAA/dsuFdqZ2zFqBrQFvM/nemMVMHlcagEDMwPj+LX2P1/+DEFuRCqYTTsNgGj4dgLMoMCPqYzUYr7AU7nvtTftZQDAPlowG2SdJabyXDFO34A0nnQHz+RVQ4Q1/jchEpHMDVtHi14NqT3kXW7TvRBmoZuUM1G8JKatKLsiFJV+ZzXUjZuxRsFpAAAA",
    "category": "lessons",
    "group": "junior"
  },
  {
    "src": "/gallery/lessons/middle/middle-001.webp",
    "thumb": "/gallery/lessons/middle/middle-001-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAACQBACdASoQABwAPu1iqU2ppaOiMAgBMB2JYwCdBaglHNpug6OnG2gWDfqP+AAA1vE3V9PAv8wykoqYOqZiOEwUmIm29FMiHXeYiepBn4HTZ8Zg77sWpCtBlfHYfFEW/DbSQYxt3KmvAl5x4KQWIpmE0NL7aSCtoo7zgvzNYQ2soCIVU/Zoo8eoD2hB/Yn8AfsPl41LP+ZuQynsrFjeB2EcPNcpQQh3VVLzIdgAAAA=",
    "category": "lessons",
    "group": "middle"
  },
  {
    "src": "/gallery/lessons/middle/middle-002.webp",
    "thumb": "/gallery/lessons/middle/middle-002-sm.webp",
    "width": 1280,
    "height": 960,
    "blur": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAAAQAgCdASoQAAwAA4BaJZgCdAYvNdZhm/agAP6t6DU4Drwupqj8rEO+ZWQ16n+3yoF5XAQBEKTEwS3KKk2pv5CTtPwi925w8TipTy2Us7nCMGEclQ9969qCi+F7StlVUFz9uFqpNNYnv22k854mZSQAAAA=",
    "category": "lessons",
    "group": "middle"
  },
  {
    "src": "/gallery/lessons/middle/middle-003.webp",
    "thumb": "/gallery/lessons/middle/middle-003-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JQBOmUABQi0xNxSEbs7iiAAD8XVYzX89Cvjp/Zv5w0AVTYqbom7lyjo3HWM+Y/I97uJ6iThiZbKhUlQRXwAvQeKiZT2uf0qcG6KAc8iYPAfilUHStCTLf858jel2p9xXP2YHPIF0Mi/b7/sQMcS5zuHKHNdKgMuh3pvGSDqc87fv+mJBlu8o6rsAAAA==",
    "category": "lessons",
    "group": "middle"
  },
  {
    "src": "/gallery/lessons/middle/middle-004.webp",
    "thumb": "/gallery/lessons/middle/middle-004-sm.webp",
    "width": 1800,
    "height": 3200,
    "blur": "data:image/webp;base64,UklGRuoAAABXRUJQVlA4IN4AAACQBACdASoQABwAPu1iqU2ppaOiMAgBMB2JYgAu9UWto3hMilG/PuLaSrHg9AAA9zNxTdsy+OO0qdPIuAw0SobT7L9stvZpwqU71zWOV7B07LJokvKjaEsBOI6vUhXI34IEQgT/5s1Uxyoeumm9tOwErJ3/gLn8bz8ktm4w70KgPnnl3Azg0LwW82d+TIxBtBK/B1XVw/+VUWst7LfR7NiUr6YYfETexqu040egzvp1o1Wo6UNtVJm9WkibuAcH96ZVdQVtxDmDTsSBXU57anRTqMnVQ1yCkH3JB9wAAAA=",
    "category": "lessons",
    "group": "middle"
  },
  {
    "src": "/gallery/lessons/middle/middle-005.webp",
    "thumb": "/gallery/lessons/middle/middle-005-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JaACdMoR3AdBklEanjSEnoVAA/smeI10/lzvImvFDMgtKKtPsgZdsdq3/Q1oqkszvtyBpWA3xxicrrE4UX4VDwvnTlZgpGNjQofBRS91Z/FVxaWHZ3DuEWcQwA9h6FWrsXO84A91iUfDX+WIENCI5ZIDaoMEUNvfIEFgL9SOdIqJhq+CoGwsJamP4JUgA",
    "category": "lessons",
    "group": "middle"
  },
  {
    "src": "/gallery/lessons/middle/middle-006.webp",
    "thumb": "/gallery/lessons/middle/middle-006-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAACwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JbAC7AB0hr2Li9h7jYAD+0+d21zweYttKVsQMF+xpEnQYn2Ri/XY3O6u8LAKWwPGjmxM8f0Eb74YSKmIeGGeD2IIYIT2xs6+TvF+axtla3/nhex78koSnyx/YQ3iR1Zxj86tbtcvPOqsrTqQ/pndrcvmxtxq/FpH9xxKpGgAAAA==",
    "category": "lessons",
    "group": "middle"
  },
  {
    "src": "/gallery/lessons/middle/middle-007.webp",
    "thumb": "/gallery/lessons/middle/middle-007-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JQBOmUABf4nv9yNRZ8dTtFaAA/rPp6igfhESlvQ60SqW5i1YMCcOpTLJI+Zx4VlyLMKxnOshD4gMuypSz8sk6of7PG9ZxGORPSH6D4DpdLs2s3907Sw11sOV4zhmBlg2I4y7OJD244NfVMS4AG+RfNT4dv/DgaL8AAA==",
    "category": "lessons",
    "group": "middle"
  },
  {
    "src": "/gallery/lessons/middle/middle-008.webp",
    "thumb": "/gallery/lessons/middle/middle-008-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAABQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZAC7IIjDCIutd1f7IGvyha7sAP6fk6kpzElGw7jhdeIXPX5iWmHYWPy3KpPUDYJ0khJ0JrAVSGpOxKDzJ+vF+gh9w6hvchEqfinr/1EraiQONuz2KvP7N7j6JfzDaV9t9pqqbugvg7AsJtrqZn9zuYd4AAAA",
    "category": "lessons",
    "group": "middle"
  },
  {
    "src": "/gallery/lessons/middle/middle-009.webp",
    "thumb": "/gallery/lessons/middle/middle-009-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAACQAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JQBdgA4R4q6VjMCgAAPzcOvVJvovD5YUVhwWw8UpOUrxppzGxYRHEK4WoCfzDoZtqSELnaPwAxXspS9zcyQp02KoEczk+iKJNeoDxJzQndyTAPSjwGPufF5dKrDW+hNjGtY/y3F3ydqKiurIpWYveMA/eX06l1U6DAgAA",
    "category": "lessons",
    "group": "middle"
  },
  {
    "src": "/gallery/lessons/middle/middle-010.webp",
    "thumb": "/gallery/lessons/middle/middle-010-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JQBWAZYMMAQHONjTFFLFfgAD+m5x0yC501/pWlkNOoNCPZTcW7eQPUG/7ghKxkyB54U46WzpA89JRm2a1FZtaBNPE8kD560TMqp5N+z9jFsx55bmeKleuzBDc4rTzy/Rti/Tj6lsGRkTAxDyUQRQA",
    "category": "lessons",
    "group": "middle"
  },
  {
    "src": "/gallery/lessons/middle/middle-011.webp",
    "thumb": "/gallery/lessons/middle/middle-011-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JQBWAAzbvKu1Q7AStwv7vwAD+awt4/HnvEfUIB9a4IK7TXeH711ID0y/esIB4KxsHfdLRtcq74PWajEcmbJgwzIJtkHDCT9SiuMvl+VoIxIDd8UJjsyQ+7y4FukSz/nBZskjjj/U/DYrsAAA=",
    "category": "lessons",
    "group": "middle"
  },
  {
    "src": "/gallery/lessons/middle/middle-012.webp",
    "thumb": "/gallery/lessons/middle/middle-012-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JaACdLwABP96ZlLjd4gqGAAD94m/hepbkLD7aesfGsnyNdZl87yVTPNcqkpB1mDAPxF1dls9NXb2H8eC3yh8337NhNhiRMxYqF3MDW7AI6EJEC92X/42S1loqPuh8B61vIsYt66laLGCiMLWWaVtBkgHAAA==",
    "category": "lessons",
    "group": "middle"
  },
  {
    "src": "/gallery/lessons/middle/middle-013.webp",
    "thumb": "/gallery/lessons/middle/middle-013-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JYgCdABL4lhXvBAjbJ7Z9AAD9jkcCkV4jL/aNTsnDQSUVTLinxKxAmuSDmdeNpXh6sRqjdb22mPt/Rnb1Paf4mbcFB/ddlCz6pz7FAB1ywaJcliVUQMqeDQpOYEQny7+jm3SD8MS9rNmaypVtLQJN6IA6N4p2QkA0oAAA",
    "category": "lessons",
    "group": "middle"
  },
  {
    "src": "/gallery/lessons/middle/middle-014.webp",
    "thumb": "/gallery/lessons/middle/middle-014-sm.webp",
    "width": 960,
    "height": 1280,
    "blur": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZgCdMoABrQjPAGT3dThQAAD9jkcCkwx2Z+lfdl/XIVihljG4W3xRkWkMKSoNWX128M2A46KgDZweiGsxHuHCBHpEX0S9HACVZ5YDd4VE01Fjs1F3X2GxzvPIHqn4PzslHK+mJAn/mRrWpIZpn5/pBJKSPEM/hMOo9exRkngMteAA",
    "category": "lessons",
    "group": "middle"
  },
  {
    "src": "/gallery/lessons/middle/middle-015.webp",
    "thumb": "/gallery/lessons/middle/middle-015-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAACQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdMoMrasACEB8/RfKmIHZ40GAA3R9EgyumZuO41su/0f5AB61k5Cb1UWNsZJUgflNpNsbxgXGHfqm1RzDutknTtfuAfM4qL4y7mbXXExQ3dSTZDlvELfgtOfKutHkbWRbaiKn8y21B6A2A2KxHd2pWEoqxVXr1Qf94rxqfBOF2wAAAAA==",
    "category": "lessons",
    "group": "middle"
  },
  {
    "src": "/gallery/lessons/middle/middle-016.webp",
    "thumb": "/gallery/lessons/middle/middle-016-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAABwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JQBOmUABeKKlo9YnELgX0zgCnAAD+2fx0Ik9YomrmRFS9WUBBQCTqcrbpD6QLZzOV/KvjxwcmVICeCbEyK2TQew2dzDfQhbzBuIfs1JgRgr+Zfy935yqj67MAArC221JSXKf7fjXCsjopfSYPbR8D53Ym0ZGCd7Nz3X3b9evSAAAA",
    "category": "lessons",
    "group": "middle"
  },
  {
    "src": "/gallery/lessons/middle/middle-017.webp",
    "thumb": "/gallery/lessons/middle/middle-017-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRsIAAABXRUJQVlA4ILYAAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdMoRwAdDc5JXZ+y+zLMAA3/OshO0B43cJa0qBubQljpqxjoidnnz2Hm5fupKwdtyx91O26+jWyZe0N8Zxq9ORnorPw5MyyzuSCLN/6Bm5rpzOVcK/rB4fB2lTDOvuJ9hU9pH0bucOxvKK5gETDT2kfBS6dSQwSf+ZPJ94FghF2K7X+QvglL85ELKd9/IhpUr8XeWSaLs77WKAAA==",
    "category": "lessons",
    "group": "middle"
  },
  {
    "src": "/gallery/lessons/middle/middle-018.webp",
    "thumb": "/gallery/lessons/middle/middle-018-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdMoMrZC9nTM79TGkj1gAA/iceHwaSUIt5I540TSMQxRoZdw5M5xCr1nd5KD8OzajlzM8y6GB1Sj0Ya2OwHygpIG8uME23aKVZyLABvz8yU0wSpEA3X7vt/KkzPpzor8HEdUFEUAMPBdJ3cwJVe2WPFu9UHP+DgUTRGOulyea+tJdOMRYUC98lgAAA",
    "category": "lessons",
    "group": "middle"
  },
  {
    "src": "/gallery/lessons/middle/middle-019.webp",
    "thumb": "/gallery/lessons/middle/middle-019-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAACQAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JQBadAbMS0QXv6yYAAP7Xa6iT092yBdI3sPxNQhYqltUvIkYb0j6Qczg5Zz/yNFT7UuTwv0i+WqSs2AnihgBHm3JasIpZ0ex9NBAAAAA=",
    "category": "lessons",
    "group": "middle"
  },
  {
    "src": "/gallery/lessons/middle/middle-020.webp",
    "thumb": "/gallery/lessons/middle/middle-020-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JQBYdhCtB6rcpHANJ0R/44AD+ZlausLKvusKcVH5jI3p8zS59Rk0Y5Cn39BNWSzLk1KiNuBUSN+Q+k55cRdyFRg/MpbMdGLlcAUilcbZ+Ril9vMBdy6+9BCGOkyVcFey16WnbZv4kYwE4tvm4n8BGyRitUAAA",
    "category": "lessons",
    "group": "middle"
  },
  {
    "src": "/gallery/lessons/middle/middle-021.webp",
    "thumb": "/gallery/lessons/middle/middle-021-sm.webp",
    "width": 1800,
    "height": 1350,
    "blur": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAQCdASoQAAwAA4BaJbACdACDaVoVwAD9tnF+dKZ31+qxSny18trha1Qlc2coMMQzeHAaCsZ3jPi15oTFOiBjJwhl3toP7ESj+9hcZw18U2EbRlg2QAAA",
    "category": "lessons",
    "group": "middle"
  },
  {
    "src": "/gallery/lessons/middle/middle-022.webp",
    "thumb": "/gallery/lessons/middle/middle-022-sm.webp",
    "width": 1800,
    "height": 1350,
    "blur": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoQAAwAA4BaJbACdAC1wAESJ1AA/vS/0dCIDRFwLGXeVmL3PW33FMtdNl3X4Atbk7vSAQ+E2cw/f2Q5/VIAEeimC1xy8/2FX2GUru6dIawAAA==",
    "category": "lessons",
    "group": "middle"
  },
  {
    "src": "/gallery/lessons/middle/middle-023.webp",
    "thumb": "/gallery/lessons/middle/middle-023-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAADwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JZgCdMoAluAileMOkhwWAAPzsdMWsGXU2YgiyrJfGBodxTfDvkBfiz2Bl5GPYQT4YsgyLl0Ek6OnSHq+r+qEa2NNHVBiPiEZbs4PCpvWqJSQUyqTkr58gfOw8N0B1/X888iku4Dgd4o66llxrUrLMnxIqvQM8AUeAAA==",
    "category": "lessons",
    "group": "middle"
  },
  {
    "src": "/gallery/lessons/middle/middle-024.webp",
    "thumb": "/gallery/lessons/middle/middle-024-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JQBOgA9JA/AdktMmIAIvf8AD+jiWUJjEvBESApIYlKs1BWD9ojDujsjwGNAEwtUNgQAXPAsw4qoJ7wCcWeL8ewvLynqS143yJRCTi2aRD6uE4gkRcgLR2brWImlpwkO2rImf9uxM0AieE9X6D/GOitU2QsV5GfgAAAA==",
    "category": "lessons",
    "group": "middle"
  },
  {
    "src": "/gallery/lessons/senior/senior-001.webp",
    "thumb": "/gallery/lessons/senior/senior-001-sm.webp",
    "width": 1176,
    "height": 1568,
    "blur": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAACQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JYgCdMoKPBFIAFeRbleSgmOySYgAA/oLThih+Wi2MbbdL9fzK2ieQxCs70AvgiSpzMoWZMqnP0PxW3EvF4V2725n1kGclXXNjhY7pTJD5u+xY9DG3sP7Hk+CHpHXu2llHjj/sbfPToAthlnRd9WlYPT1etnfk/cUfVvEVxUACf4SRdB943yMmvZQ/0grsAAA=",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-002.webp",
    "thumb": "/gallery/lessons/senior/senior-002-sm.webp",
    "width": 1568,
    "height": 1176,
    "blur": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoQAAwAA4BaJZwAAptilN3tgAD8pzpc8dCXuoR9EJeRi9bYWRfzvRFm/cYaVCXbpw9LMAAA",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-003.webp",
    "thumb": "/gallery/lessons/senior/senior-003-sm.webp",
    "width": 1568,
    "height": 1176,
    "blur": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAwAgCdASoQAAwAA4BaJYgCdAD8vbu9G4qMAAD8pUcV5TPNM6sUEBBCKp2erhPOGkBm9e9CdL0h+GsQHKFIDjVi47HBHNXcoCe2ZSbqszWwLWFmfUBzGHXRwAA=",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-004.webp",
    "thumb": "/gallery/lessons/senior/senior-004-sm.webp",
    "width": 1176,
    "height": 1568,
    "blur": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAwCdASoQABUAPu1iqU2ppaQiMAgBMB2JZwDG9Bh2P8UZHNhQaXpgAP5TD/ttlE1muG0nzF5/H9XnpJXmH9ABgyt0g7kKTBLwGRue8mjY6AAA",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-005.webp",
    "thumb": "/gallery/lessons/senior/senior-005-sm.webp",
    "width": 960,
    "height": 1280,
    "blur": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAADwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JQAqkcLUdkfBYnIXD9OrAAP5NcTVO5GEYGPN08f7QkBVBJoSm93HELM/smPSEH/M6ppc8MKQJT9tDrvUcH3JoNlfFHwIwZa/HmWSfcx7b5TEAhxI1bxrH5MXlEj6+A4LhsKs37heGnJf8MfwKKbrLOEmhmwRta6WIqhIgV7Lw+v/N4AOAAA==",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-006.webp",
    "thumb": "/gallery/lessons/senior/senior-006-sm.webp",
    "width": 960,
    "height": 1280,
    "blur": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAADwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JZACo9BxMN5dkKuxtNnLAAPkIwKj2L/Cms6nd31wBdgYmI9G7GAic0/ssJAh37SBOwWyAVMskbndjukXToODhnAisvnz6xhBSkYGLUvvstl4/5GwCiEtOEV0RZ6wGtalHzj+uZ3EeNNxj2QQL5Rn32D1tAAAA",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-007.webp",
    "thumb": "/gallery/lessons/senior/senior-007-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAADwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JaACdH8ACg/SM8ZL8JfgAAN9S3VFFxqdl2BwZD8LFGByPAaTl08d/n2qlXI2ipcVVJXf+nKphtJILNKxfzJyjm/2+wVEtsE7Oo/2mw/1p0uajP1szpm+Cgb+WgnQ5F160YLGlDwjCb9JzzOUS1rxlarN0G3r84AA=",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-008.webp",
    "thumb": "/gallery/lessons/senior/senior-008-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAACQAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JQAAIbt07D5vR+p2cAPzP9pUboyC88MQfCZHX6uhRgnuEoy8D820lsxecw//f/+TkG05XxUUndg/ld4vowX4E3KgRVN7DrUKAK8nfIVrcQPAoPfwxUXdywL9XzMWGRrrcuOvvH6LZeV8//ku4AA==",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-009.webp",
    "thumb": "/gallery/lessons/senior/senior-009-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRrgAAABXRUJQVlA4IKwAAABQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZgCdMoFWADlhkfxB2cFXANw4APuWjYYEckKUFy77NoPZ9at1beBwSGPYfL8Yti6vketAn5g1r7VZQrp3p5aCfEc9eRM7m9cDtC9yuJqwNYXk5NdJXv8LT6ER3nGZ1QJan6k4W/yetg66r+mO2jlAL6DKV/dKM3ww4DELcRS4ccV/Jp9xSFtojuvLxECjUyUvEAAA",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-010.webp",
    "thumb": "/gallery/lessons/senior/senior-010-sm.webp",
    "width": 1800,
    "height": 3200,
    "blur": "data:image/webp;base64,UklGRsIAAABXRUJQVlA4ILYAAADQBACdASoQABwAPu1iqU2ppaOiMAgBMB2JYwCw7Yx25PYX/eMHg16Cpo2Q82OIAAD+wQnfZkbrrmrFlFmS30F4Biecb6b21M6z3lEi7mt9ow8J0WkH9zLx8moUdE3lmGFOodibp0byKuh+tFkSPicWg3dyAdYcjYGTAXmGRKua8rUWe4xE0PLCCVP+J7ML2glG1fD/4O90CTtdlfG25Gddg9ANCrRwz7/jw5q5Zlj15MalgAAAAA==",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-011.webp",
    "thumb": "/gallery/lessons/senior/senior-011-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAABQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JYgCdINignxZfs/r2pmLHL1JAAPywy9vou/fjsrmyZgJwQk06oz6mYML5jC/KLuyG2X8YKMuRAhpK6hx6d/dmjS5h6S/qX/J2Pz/ljaJxeZ+5vXv53c8XOSB3+j6pSCpSQtteyrrhCk0w4qv3+r773f+8ga2PJ2tuAH0Xwv/KC21R/5sujg4dK5kMG4vsIgAAAA==",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-012.webp",
    "thumb": "/gallery/lessons/senior/senior-012-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAABwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JYwCo+3gGy9Q3L3IYOCfmF9/3AAD+xWeJvsPgYqAaf9atT38Dhkg7QACEn0y2g/WmQnsdeb0ahur4E0/bP47O687o8qbGEDp/1wks/+b2LKN1DjoQ7iawX9t2w69erAo7pbCSsxmTPjTYpAe/5qRFeyeJYobZy27Bt/+AAAA=",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-013.webp",
    "thumb": "/gallery/lessons/senior/senior-013-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAABwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZACdMoADab75W3fYDyKFiKEYAAD8izyWkPauof90a0kWXjkGKjWGoQ83Jo5HxadrD4ryssXfgCvSlTIP1bzvJQLMxejsyKSl3YqfZLzNZnLku011NBqo8bP6m57f04yU/844baGW8ELWIG4tG/rQDDdc2D2W4sI7KdaIn8YS/RZULIiuqAAA",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-014.webp",
    "thumb": "/gallery/lessons/senior/senior-014-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAADwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JQBOgMZKJ+jmUO/arVAoAAPEHsxUhu/DuSDqOthtdg8NjKwzzrKrEY4J5+jld7c4s+6Km3PFDKY2R7jURLbe8d63svo4Z9lZHO6SPQuozBS+ewvBPz1Cciz0RbTNeAaoz1Cl2R/fM9OfYIcRHiiFK96O3lx20sYPZpXbD0LkGsuz6a6cwue6Vi/4E4AAA",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-015.webp",
    "thumb": "/gallery/lessons/senior/senior-015-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JaACdAYxi1aeWPVLbEYr69QAA90L++6SxR6mGBTYRz+pO3qQS975R1BEfoNyLM2Qj+jBiqF0syVLuXuWAsL7Nw9ckGw5NN7oofx/BY0pZkbSdXObPMFs/W47+sH7NhF/kWsEdWanQULHhUH3EfAAA",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-016.webp",
    "thumb": "/gallery/lessons/senior/senior-016-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZACdMoBkgAnIyVIrLPUmsuAA+6N0MThWfnMtehDCsZ3inRehldPbdeDe0ZEiJQS22pFa+Ky+qm01NEszQDo6S2z8LwVDPPPobH40XhLIxlveKvFm0EDARlNEfdmWbnPIrWtjAnFlqRVrHtP9QcAA",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-017.webp",
    "thumb": "/gallery/lessons/senior/senior-017-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZACdMoMqmEkz1iFa7ARpZfQA/qEisyBU397rDKx/hxDpozOvjUhdwYiZwbv/vSPtOSs0tiJCWa/jGzGIxOoFPTVUjodZtXudy0NLkyoPVrvwzHEiw8iCtvjismopmSk+XUv8/eRrL35J45OOmJ/Bqx3sBsFXL1KqzXg8kIbnM/5lqA2EBtq0F0nSyAAA",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-018.webp",
    "thumb": "/gallery/lessons/senior/senior-018-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JQBOgBCqWIu8VqLijKwmgAAD+WaJqoLcH5U4D2iJbSLfC4FkjQ7vbaX+huwen3XGPsS/S+Z6AvWocXi2etslA3iK2cZt/FQ67sqnlqtFpL/Uq3pLs2HtA/YngAA==",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-019.webp",
    "thumb": "/gallery/lessons/senior/senior-019-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAABwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdMoCGABrvtc6CQ36UsULmgAD2g+YOMSL4PBnJwGMdYGgjBCK58Ze0S9euZCW+ROttFXvDU+XMGdo1dWdOQFADIoow/ES/6X13/C4cBxxsrFN3QBg6+AZa5QXvTI8tmLgUC3hb6C/f5KkMUcpE59M8rrmEBvcbw8/+bEnyDR9BaQAAAA==",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-020.webp",
    "thumb": "/gallery/lessons/senior/senior-020-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAACQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZgCdMoAlthYSaqJt+9ybAq6egYAA/szWXI7yfZwYbU3CRuSwNIqESlRZz06+0/8dMRc9mT8/6EO9rRC7rAxK8ZzKc7M/jYACEmT738kL35DLDSk4wQg9xGDwiwA0rIOfGUblf2/MLxh6DmtUnBNmAJZ9GKsVZOVfNqFSToqAAA==",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-021.webp",
    "thumb": "/gallery/lessons/senior/senior-021-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAADQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZACdMoMxgDwqFQdCbAYimy16QBNDoADw423LxeHeD3/ZbkF3ZFw6Z+JYK96PVmY2cM7z4+WY14qJw8YuTjjI5a1aJo7E5LwiM9QbCv32tz6E636U2BAJ1J0kjR+QkRCxIhRIzcdv2z0B1Xnl3rxRJZvvnqcQQzlF++n2DdcAAA==",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-022.webp",
    "thumb": "/gallery/lessons/senior/senior-022-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JaACdMoAltwr17GE970HCJoAA4fWq+sK6yjZ9nwOXPHV8kg6w0nxz0JFfC9PycyGXVm5x8Ex2LmqFCHr0Vr8U4YIYzDNjyBhSGkwXRWtrWcZ0559J2v0+JYjKT5SdoJpbPnM9NqVN2+b8Iw2ZYcUXMYtKmayMykR6ghahAAA=",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-023.webp",
    "thumb": "/gallery/lessons/senior/senior-023-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAACQBACdASoQABUAPu1iqU2ppaQiMAgBMB2JZACdMoSA2dC4z6gofszizo8DnQAA8CxIHi7FcIv2ZSHynJebqE60U9fdlxLXAWWq2YoDCV+5gMtyOhAGpqC9uen0dkkNSl7BdI+4tQrWQ1JW2mhbuOYzahnprEJytAmFXgih04oroSHbeMAAAA==",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-024.webp",
    "thumb": "/gallery/lessons/senior/senior-024-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZAC7IIjCGGih26EGYiYEU8AA/umnL67tq+jqqJL46iHEx5RZA+bBNxJ9o2UyxyKhN2xt0f+qKdwiSJr6yezqC7hEGZtW7eGZTpmbx7+DIF/ikTm6CLLu2QQreCy5HfkjgZBDAAUMbgfpm5j8cgFi7Lvkqu8uJuAAAA==",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-025.webp",
    "thumb": "/gallery/lessons/senior/senior-025-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAABwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JYgCdAYxEfvmq9tsjy2/rGylUAAD2uzBG9BXqKKNv6rBhG2LjnuJUtioGrd3RASGiXYLg2R7SpaS5IC/bDpq73g6oUZe+d5Xs11MGA2fSzwAV8ugUVAk4Py+pNSYOyON2p+DEs3WXsniQqc39aun+d+pDFGvElzndDkvC/57N7BB1TPbPdehgFtXnlZFwOAA=",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-026.webp",
    "thumb": "/gallery/lessons/senior/senior-026-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZACdMoABpAOdor4WKGOiiAD8T/cgnEGIyh72Kv8zhE1MkccOu5Za5oOjNIZF33Pb+m8CchoUkwBg/4mP/7CNrFetflQCGRUq0M+LxjX8tWC8CCc/vHRZM88JiKarZI0Ics00FXjmAAAA",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-027.webp",
    "thumb": "/gallery/lessons/senior/senior-027-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAACwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JQBOgAgMmJnAx5LUgAAD+ZDrdx9uY7oCn47ch4vyYNVUil6kDHSRICtnOtAPfo3n6cKp08JbwbUe9pts4uuYmwF37NDOpaFeFweiXnmNFYhH321zuiMqDTNLn3V4e2dvB3uj7VdXKMd7ytgAAAA==",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-028.webp",
    "thumb": "/gallery/lessons/senior/senior-028-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JYgC7MoAltg2Bb2opTct40AAA/PnoShg0W4D6dcSRv3Ejc882v+UaOHyPyNdXhSi2LXsxO67L2geTONsvC0nyf4n7F9LON6jkLVhDkWO3rTb9txjXX46nZC87oRkfjr3bGRcNd7RW3ExS6GocZXm77AjG1DoZfb9fbF2BFvYnyO468jkNIAj/giwAAA==",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-029.webp",
    "thumb": "/gallery/lessons/senior/senior-029-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZACsABxoeTYkqcg8dyuFgAD+HUFO43gRVOhPXZTdT8PlZGMD+Wuucvhm/vBjkQWqyQmZB6RWdsFySLgPm9l7oK017cvTQjuQCZmE52eBgEOIGnrltWOzNP1RkTOjcnfmmFsxSTOOulx3foudJVysy1ls6au+/8yIzd3lCwLO4AAA",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-030.webp",
    "thumb": "/gallery/lessons/senior/senior-030-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAADQAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JQBWAAuBjfB08YZwv20AA/h1v+Eobf3iOfj6gGz7tvBH8OLf+9aTY5fEImkqfiX+X3KE93iyV035OBR17QMzp64q6i9oNKQgbxamfPo8mtuvfhtrdvp4h1a73P5YONhsCG5dSRJmez3kYEmL2M3kL6pYXbXPjd4u8j0uZs+ZkdGsc8WtAAA==",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-031.webp",
    "thumb": "/gallery/lessons/senior/senior-031-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAABwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZACdMoAvQBXjQRrtrcfiWoYaAAD3gwQBQy5MdAyTeEWLCRbMdQwfgYf6GmkYtLJ5ysbfjIw0a+QzXWJIBpqLnnz4m60DJD6iJ0GF6Y4RVxnrZEyW+uMSHDYdgH0mKb1y71Xg2vzcx/OtwBxe/ega3vkveII10dP3Ry1S8rjRAAAA",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-032.webp",
    "thumb": "/gallery/lessons/senior/senior-032-sm.webp",
    "width": 960,
    "height": 1280,
    "blur": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JYwCdABSrVHNy+d/PIAD9/2UBWReM83jTtWTAjUQgt0EsJoK1ImH8kVYiQU/wfD/eiuOTxn5fhmjdTAA=",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-033.webp",
    "thumb": "/gallery/lessons/senior/senior-033-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAADwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JZgCdMoMxgDf+3sn10m7QAP3rvzM8OoPn9zDfugj0/qdsKWu2a5YHF1Yl6CM/gDYUcvK0lSFMdsxWT0QNrQY/XsMFKT+u82vJSpTdEdaKjQONsDY58/zaboWntdg47VzjJrDFpFcBXEYNH13zn8FsdQA5UCAYEAA=",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-034.webp",
    "thumb": "/gallery/lessons/senior/senior-034-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JYwAAWSaN/B4hYCHLVkYaAAD80E2Xt+6X7HuGgeNH03MesveUfG4PxLQ4MaTd0Oz9Wq5ajGmS80i61flF6usrBSFUcN1IxGmb1LrS/Z6ssy0Lq/ny91n5+q7nSzrexYbvnUdCACgJ6r+mrVID9XQA",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-035.webp",
    "thumb": "/gallery/lessons/senior/senior-035-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JQBUegqtXnN9KMGO2wq9+k8AA+MZsOiVstT6qFAa6YRQdsDnXB7ODqZe3Y5CBOg6BbmtB7fev8hu3dzThNI3KN3wcAr0nVkbE8p6ITnyzRnYWBp70jyd4YHtUctLm5hEiUFWuLuO5yR2XKLfBKAAx//HqO35q8mCQKLNa9dIuo4gVkFjxV8YHO41yAAAA",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-036.webp",
    "thumb": "/gallery/lessons/senior/senior-036-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JQBWAMYnPTZTSYHkwPk3MmAD+TH//s9AvgzGvSgkJ3nobkvRtYy/A/7pl5cosNv/gI8fwH7xETbw1CxS4qK2BfZfj24/7lWyZpUi5i1RjQ+maYPDJI7R4JISKub4AieqT7OGO2UZzqV1y/smp8an8RkOz/UttN0yBtc1mQO1xxqFoAAA=",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-037.webp",
    "thumb": "/gallery/lessons/senior/senior-037-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAADwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JQBdgA3PktT/BuvDxmxtQAP61UWFHWYa3zZVJULoQx+0G8GN50P9l4rd7xivURLxd8NgO/j4PA8iMnEpP8OWAFuJVi4/eTmUAIMfxLTqsSPAesMZvXxUde9zbQzaMXcfqR3ABuCxRzOR2cyxQVYzfyNZ7M13nNR2AL6Cap6AAAA==",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-038.webp",
    "thumb": "/gallery/lessons/senior/senior-038-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAACQAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JZgC06B9WPfk1xxHgAPfVr70iH0ojZO657fr+FW1q1Hc9jPdWuii0S6siz1zGzaB+k0UDKNberTTxzOxWeTXPjgWOUeZFUvZZXjhXEShHpiSgPD+Hr5qkO/qSz966KvMj+9TTBpTdlh+yUs8sBIkp3L30Jj1MyZeZ3k0wgAA=",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-039.webp",
    "thumb": "/gallery/lessons/senior/senior-039-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZgCdMoADy39P7Kzcm6vmlHAA/jwwCjYo095bA6wyMvMewh8ewAJqwFJNrNmFE4ayrVpSr/5ZzbmKq0z3leZuEvuZdb1d1S8fDf1QPmjL8BnB3ZvD0zpWhPaUvhQluQMR8L9zbL/VLwBwE7WJV+ppicSkvfK7TMWAAA==",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-040.webp",
    "thumb": "/gallery/lessons/senior/senior-040-sm.webp",
    "width": 1800,
    "height": 3200,
    "blur": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAACQBACdASoQABwAPu1iqU2ppaOiMAgBMB2JZQDCgYv01ZFGtMAZ2QdPkjrTzgAA9OyCjtZw5ioQjsLc9ew/HoJNfguo4QrJ15G3vJNjkBzsDCciPF22ZwEXajIQhqMVHJ1JvY5xtT6yu/XVo1/dK64kpgrJgtNdAR+bFK2mCY2WNZ10/TtaQNNhyFf9ZdIp+y2f3BLuy+uX5iYo2HgyDfnqHoUSyeAA",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-041.webp",
    "thumb": "/gallery/lessons/senior/senior-041-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAADQAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JQBYdg/JDOMbuJHCoJRAA/mgYdTFsEScc6l6JvcOrC38nZPVIdkV8W6cdumFsU8okpTyMjvNBq0I57soAkkJlSNSPHQfdvT4rOt+Njk3ZrjIMA5Ey1LwNnV0MCvLTIvaHRujY+1iL7qC84ftt4MoW4Mm0dNcDsd+J3mMgfugAAA==",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-042.webp",
    "thumb": "/gallery/lessons/senior/senior-042-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAADwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JQBOgMX6RPsNIjnVcoNoAAPwQiAr5FxfzB08WDBh4kbhBFDAg7Hws787+TYWR3+jyYOE3dyXr2yyeLIKQlZ4T5pYTQkoRxRMv8+KaRAK8Zuf5h+8EfYl7/G6qApBpF/NMiVsD3puU5TiWbbHRMbkd1NIZtBJbWbGwex8BFyBHgAAA",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/lessons/senior/senior-043.webp",
    "thumb": "/gallery/lessons/senior/senior-043-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JQBOmUABBHLDkaXhrnWZOAADNyHuJkUwIPJ7JzN0e6B0LD1faGVBtRSyUO+Qw5A0+M9btnIbBUddS4uFC/IY5emeQBIfvgr3UK+xaJeed41gnnbvvhyyk4yL7Pjr761EMzmAA",
    "category": "lessons",
    "group": "senior"
  },
  {
    "src": "/gallery/camp/summer-2026/summer-2026-001.webp",
    "thumb": "/gallery/camp/summer-2026/summer-2026-001-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAACQBACdASoQABwAPu1iqU2ppaOiMAgBMB2JZQCdAdzdhjUD6p0nB1St/IBNsQAA9zM71e1cM8US/98FUHEOjvgb2b1SCNCbmHWLs3SGyJPbUvdJy52JCnEvx56KfoXvYdWfHY5jkycv9yHJgdbS2+qlRWJOQgctvJE4cIn9HxI0uTAF1UEc4ywUtnTAELQu33pcGmEp3J9MBZDZ/147xwYF1eu0979bS9bmTpWCIAA=",
    "category": "camp",
    "group": "summer-2026"
  },
  {
    "src": "/gallery/camp/summer-2026/summer-2026-002.webp",
    "thumb": "/gallery/camp/summer-2026/summer-2026-002-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRrgAAABXRUJQVlA4IKwAAABQBACdASoQABwAPu1iqU2ppaOiMAgBMB2JZQCdAYyKgqMwm/p/o7g5iGbwAPglgSK0lYgvTRt8pDeDps6qKc7kGhsv8IqMwSp7nUKLQ8s0E8gMlRgCQBXetFXkNrI1y9uzeIG6nUlkmkhSrZSuC6RgXXbmqcNo5x2wqHnVNVuh21mnkf24OHpRPRM3giZVfYh3oIsJJ0laMJlRmW+colXqNMqDvm9kW2GnGYAA",
    "category": "camp",
    "group": "summer-2026"
  },
  {
    "src": "/gallery/camp/summer-2026/summer-2026-003.webp",
    "thumb": "/gallery/camp/summer-2026/summer-2026-003-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRrgAAABXRUJQVlA4IKwAAACQBACdASoQABwAPu1iqU2ppaOiMAgBMB2JYwAIEC6Sk5lOPLvzyU3f/31MrhgA/sbL/KY6l9vdRkjHhESy3nYzcMHgFjdNXu/1e99uf6uwKzYAscgJNWhTri9l8hc7XDhAsvt1I8VYskq4PZOKn6E6B2Bik2H5/DKnGb5znMTWjKidQ7+SDSZlNAtYJdHtvkzDwENexhWZYMunYWmjJ8P+GWjwUvP7xMGYAAAA",
    "category": "camp",
    "group": "summer-2026"
  },
  {
    "src": "/gallery/camp/summer-2026/summer-2026-004.webp",
    "thumb": "/gallery/camp/summer-2026/summer-2026-004-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRs4AAABXRUJQVlA4IMIAAABwBACdASoQABwAPu1iqk2ppaQiMAgBMB2JbACdAYxE2//w57bvmg/kKxuT0AD+rqOqrDecbOW47c92acq9TWwVeGrvFT5y520jcz9sahHIRmVNiRhmQWRALW5jcYO+sY40AEkJVpxq1+y7biDzhG2cQ3EM0vXhdVNdEh+aBoeHHCPeRNhVm9AxVcN1NxZNLsDQH6fMR+uMY7IF+oAGhJl9khMGoEGzu7J3gNUvzljPwcJLYaGpzX9wfzLiYBXyIAAAAA==",
    "category": "camp",
    "group": "summer-2026"
  },
  {
    "src": "/gallery/camp/summer-2026/summer-2026-005.webp",
    "thumb": "/gallery/camp/summer-2026/summer-2026-005-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRtQAAABXRUJQVlA4IMgAAADwBACdASoQABwAPu1krU6ppaSiMAgBMB2JYgCdMoAltkna93bH+Wwr9yLgTG0mAgAA/vftBWlIpjuGi83YzH5wEkc49xqJEQi5PbmH7kTj5e8kFGcVZiXVvvfOqn315MSt4qkHBF3Iw7JHTcy+Yngf+xZJb8EqIurmL6bczeig3eld4TY4bEUVxMLosV0107zpzjuxKBZZaHKQLUEbiHbfYd9qz/IEAnVHbkF5SMxHxTlEos3DHOoPz55OK3CLVbYjnLpiDwAAAA==",
    "category": "camp",
    "group": "summer-2026"
  },
  {
    "src": "/gallery/camp/summer-2026/summer-2026-006.webp",
    "thumb": "/gallery/camp/summer-2026/summer-2026-006-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRr4AAABXRUJQVlA4ILIAAACQBACdASoQABwAPu1iqk2ppaQiMAgBMB2JQBdgMZPPW39jos2vWM5JIVPtgAAA/HGmwY9tDmWMia2c/fpouJ5RH8QTwB1WlRnSmDvfTMqay1vmCHNNU8twjPPonLPfvNpfCfBvV4cQA/aJ9dvFnDfX5bsUeohxzzD7Be+3/gAnpgbWidRnTbk8vhud2iq4JJ/2f/Xho9S+iq/KpAiHW5OvI/apx3X/ZU8YD7EBt87PyGAA",
    "category": "camp",
    "group": "summer-2026"
  },
  {
    "src": "/gallery/camp/summer-2026/summer-2026-007.webp",
    "thumb": "/gallery/camp/summer-2026/summer-2026-007-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRsQAAABXRUJQVlA4ILgAAABQBACdASoQABwAPu1iqU2ppaOiMAgBMB2JagCdAywTlwc617zxnK+bkSYAAPyK1kwc0Sav4hOV8Hg0kidbMYXxtwrSrRPerd7HUdQzQbswSu949YmFfVQZYkmxeuJU6YkYi9gXVSZ1bBk6C/ecRqxOQiqM4X9grwEpWNd9ViFlygPgO8jrpTrO8OOM/RHJpx7DeeEI733UnwE2Qlt+tQSkW9gr2hvvlHa5cOiy7qeNhv6wt3PQFgAA",
    "category": "camp",
    "group": "summer-2026"
  },
  {
    "src": "/gallery/camp/summer-2026/summer-2026-008.webp",
    "thumb": "/gallery/camp/summer-2026/summer-2026-008-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRsIAAABXRUJQVlA4ILYAAACwBACdASoQABwAPu1iqU2ppaOiMAgBMB2JbACdMoAlsxZFQtT/2YOfYHDn2QGAAPeu8mlkXO0CBH04gXVZ/rwyNOvOC3pBQ+FYpY1rVe0usAnCV1UyJho4R6Ug5VUBjKwfVYrBgpLi1LzzQQPNH195ltbJ8BiqJS9ZiF0WF/rq4FAveW4zseJ2fUVQvoBXWowCET86xAgzkCrP6B+tHPv9q5B0Eq6DbUK+rWdjnGkJNTQiYyAAAA==",
    "category": "camp",
    "group": "summer-2026"
  },
  {
    "src": "/gallery/camp/summer-2026/summer-2026-009.webp",
    "thumb": "/gallery/camp/summer-2026/summer-2026-009-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAABwBACdASoQABwAPu1iqU2ppaQiMAgBMB2JbACdIMj2LwJj47sGxv5xNvu3cAD9+ai8iCZAC343azBrwUnpD5hftvW2CJvOkHRoqzM3AJ14uRX9Ab/N8GWwyQmPoND+2nLALLCV0V8k15mLiWxpOzCAm+vERwQwQNr8Q5d2OO1c0aqQcZGkf1ucUrnXahPdfE096/KhfiURNp+7qX85DucIf7YSR98ii4SgAA==",
    "category": "camp",
    "group": "summer-2026"
  },
  {
    "src": "/gallery/camp/summer-2026/summer-2026-010.webp",
    "thumb": "/gallery/camp/summer-2026/summer-2026-010-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAACQBACdASoQABwAPu1iqU2ppaQiMAgBMB2JbAC7MoFWASgAGYPVZOwtiuA1HGAA/Ox5CxyqPWsXH/baiDrwdVQbiYixhHjw9zJXHTC4cJjI+eZqRE88vrTHtJKCmnfKjxHhXHt5rvKIGm9ujBn2Rak0MB9aqQX0t3ictayS2hdGZsGDSrHjeIGaUBdEAOdQkLjDgAAA",
    "category": "camp",
    "group": "summer-2026"
  },
  {
    "src": "/gallery/camp/summer-2026/summer-2026-011.webp",
    "thumb": "/gallery/camp/summer-2026/summer-2026-011-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAACQBACdASoQABwAPu1iqU2ppaQiMAgBMB2JagCdMoMxjBiBK1iQlVGdKPu4CcAAzWeMDtzUTXnUup1OO1nc0ldUvunwo6ebgYgv8eaPOWvBSjeX0d8q+dklrR8f7zfWDT6C6Dl42BvdSUpS3HUSGo9ImsbrkOt+JaZRxUtlZBOl05qWzT3FwEJYh0mCIuyoowc9xpOIho569mVBw+ZPdboEAAl3DKl/gAAAAA==",
    "category": "camp",
    "group": "summer-2026"
  },
  {
    "src": "/gallery/camp/summer-2026/summer-2026-012.webp",
    "thumb": "/gallery/camp/summer-2026/summer-2026-012-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAAAQBACdASoQABwAPu1iqU2ppaOiMAgBMB2JZQDE2Gf731spxdr8cG2oAAD+ZkLrWZgOpTAjBnODBcB/miRtIvEcg8XDdvKZ/j9K63ZvqJXiKNtmMf0xuH6TL+CIES51DHR8TGarZ90TAzqHUsiYwJOOm4wNULPnTQSYAA==",
    "category": "camp",
    "group": "summer-2026"
  },
  {
    "src": "/gallery/camp/summer-2026/summer-2026-013.webp",
    "thumb": "/gallery/camp/summer-2026/summer-2026-013-sm.webp",
    "width": 1800,
    "height": 1013,
    "blur": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACQAQCdASoQAAkAA4BaJYwCdABoXJAA9AcVxDOnae1yvPOwgGosVkZLwC7qKyMhwlpJbNVSW1Gz0yyPzpTZmYAA",
    "category": "camp",
    "group": "summer-2026"
  },
  {
    "src": "/gallery/camp/summer-2026/summer-2026-014.webp",
    "thumb": "/gallery/camp/summer-2026/summer-2026-014-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRtAAAABXRUJQVlA4IMQAAABQBACdASoQABwAPu1iqU2ppaOiMAgBMB2JYwCdAYvMmA2zVDbZkfnBFC+AAO/VqMWKzYW8JiDmP0ysO6JSSwTJKfv00w4fsFeDlTFiK1dI9MYwfXMDxbzL9q44cmfscKOjK2NepiVjRVF3vYZqBI6WZeu5w/YXgjVwEtCZKddG31B6ZURVCaE7OhzdMNqW1Siia5NKb92t29l4y2ySVUPIP+Tsv9Y1xUtAQWCTDw+sBXNxXdW+yo9uFEY4boy199xngAAA",
    "category": "camp",
    "group": "summer-2026"
  },
  {
    "src": "/gallery/camp/summer-2026/summer-2026-015.webp",
    "thumb": "/gallery/camp/summer-2026/summer-2026-015-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAAAwBACdASoQABwAPu1iqk2ppaQiMAgBMB2JbACdMoACryKoOHswGzcXOgAA/SHcNccTrM/hSa8cMlVSXtgJytt85ulDf/iWvpz3qxumrlAOqsrJ01uuN0DadTTXUpDuzt7avb9Tnwqq/zPo5EwgFFFw0oKdydKWm7G4WlhFj7Lze7iAAAA=",
    "category": "camp",
    "group": "summer-2026"
  },
  {
    "src": "/gallery/camp/summer-2026/summer-2026-016.webp",
    "thumb": "/gallery/camp/summer-2026/summer-2026-016-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAACwBACdASoQABwAPu1iqU2ppaOiMAgBMB2JQBOmUAS442pn/p8hBjTrRC5I7p4AAP6WgvT5qYkkJXi8KZp5Ehee9swQL1FtnXO7yh5EcfeAY5ocxImcPu+RfvYIvE/mIvZ+Sxcr8CIH3gRIDY0ZbHXsMpScIMIwr2vldW27ubeK+TqE3GnyhvskUvGvE6uVByTABywqoXkveHexkj85qP4VS7MwSBGgAAA=",
    "category": "camp",
    "group": "summer-2026"
  },
  {
    "src": "/gallery/camp/summer-2026/summer-2026-017.webp",
    "thumb": "/gallery/camp/summer-2026/summer-2026-017-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAABQBACdASoQABwAPu1iqU2ppaQiMAgBMB2JQBOmUAS2YvYrwBQwlc2kPXdgAP38t3PlKUABuCAmGY3GtXhtjPTHBI90McQtTT+IUWH+DJ4M6h84HEdeHoQpQLZ/oMB3XRQEQbFDmvKDkJnwG+AqfNZScnyLgPYU8DnPuuuUH2sMOqXsykgQr7PktU6dhXuuxa10uJ0nCFgvf0WkoaIpWODgFYgAAA==",
    "category": "camp",
    "group": "summer-2026"
  },
  {
    "src": "/gallery/camp/summer-2026/summer-2026-018.webp",
    "thumb": "/gallery/camp/summer-2026/summer-2026-018-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAACQBACdASoQABwAPu1iqU2ppaQiMAgBMB2JYwCsMoAC7XUqa7p1feev8sUZQAAA/gKggRza7yi8hYFsTQm79mdLWHlrrk+2XMMF0UYNV2xttLBatZ2Dc7pcDlPrDcXH0ENvpFz8b6MOsR8G+Kqzw9svBoaBwQvrApA+UsJqbM717zPY/RKfJfJ98PqfTcmP8xC4r2zns0yeFguKW9CB3oIA",
    "category": "camp",
    "group": "summer-2026"
  },
  {
    "src": "/gallery/camp/summer-2026/summer-2026-019.webp",
    "thumb": "/gallery/camp/summer-2026/summer-2026-019-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRsgAAABXRUJQVlA4ILwAAADwBACdASoQABwAPu1iqU2ppaOiMAgBMB2JYgCdBrANx8wOtu66YZn6dFzFzwhJFMAA/lW05WZZ1w18+fcDr9CezQJuI6Vpgb4SHPC2gdeJRRofAOgu34+3gQWskx8STEAvtSjfTVIE00J6ea6ptI24yz1XwUlgzVuVNmfLikCMcdRScadiGI7fCRmaT59fx0a6j6zdJudmsOd2WPSrPWnw+/lmeRIKmlQAzZ5djeK2fVWVdFeaqCkhEF3AAA==",
    "category": "camp",
    "group": "summer-2026"
  },
  {
    "src": "/gallery/camp/summer-2026/summer-2026-020.webp",
    "thumb": "/gallery/camp/summer-2026/summer-2026-020-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAAAQBACdASoQABwAPu1iqU2ppaOiMAgBMB2JQBOg7wAROoadY780u3u8AADNObp8JHQJZ8nfLFdwHXmAli8FzxurxI6KbRER3FPQ6lyDCxCRzYd09nwiy/8g+HfBMrecqxOOlxeS2GII8cUPqUn0F15vvotQzZmabVyhumw1Aw0CIrDax+5+7h1RbTBtgaAx1+rdIAkK9iy/yEufsbeHK5Akn0HJZAGHAAA=",
    "category": "camp",
    "group": "summer-2026"
  },
  {
    "src": "/gallery/camp/summer-2026/summer-2026-021.webp",
    "thumb": "/gallery/camp/summer-2026/summer-2026-021-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRsIAAABXRUJQVlA4ILYAAAAwBACdASoQABwAPu1iqU2ppaQiMAgBMB2JQBOmUBDAM87PJAqPqIPk7IAA98lCyGGvSoselb89GY9rAkhCV4YcnCXT4PKW/g3V3S5uXX7e7cM8VJ19XFTZKjWZr0KOBNZSF9Tb7vuFriFt9u72M75CCyOzKTwmyE5hEldRh9lPGB9OBWsWiLZRjkpjf9QvDlruwDkrYN7bR2U9nMdMisKHKcbE9UD7jOLcRDIBM5J25hU+74QIAA==",
    "category": "camp",
    "group": "summer-2026"
  },
  {
    "src": "/gallery/camp/summer-2026/summer-2026-022.webp",
    "thumb": "/gallery/camp/summer-2026/summer-2026-022-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAABwBACdASoQABwAPu1iqU2ppaOiMAgBMB2JQBOmUABfZd0vfVHnVutv59u8gAD9SN4C/zxIdCxjUo6pROdeQZQmvSoAyLijfsJ4PBe5oK+lxn5uDBb7vMfcemcsrT99OPEeBvYagrP7XiRAkS7WxpK8n5SNJUJyUYWEp4Sst83F5T85BXCjfoh6GRc3G9flf5oILbD8UT3ZoAl81K0EQAAA",
    "category": "camp",
    "group": "summer-2026"
  },
  {
    "src": "/gallery/camp/summer-2026/summer-2026-023.webp",
    "thumb": "/gallery/camp/summer-2026/summer-2026-023-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAABwBACdASoQABwAPu1iqU2ppaOiMAgBMB2JQBOmUAnANp6XqkSWFgHFaCCQAAD3zZ5ezs3Xaf6PmnfCg8iFD/nrrDW2pQuWSF0lds3VIeKptIQBoKV9jXGUWokEjHj1xzmnygaLxNOx198Fbnfv+9hsm61RXs8i7T6OSjlBmQWhcxxNZTQrbyqw3EQJNnwuNdm5oNbLvIoFbSR8qPA6V2fZmkhMB4gAAAA=",
    "category": "camp",
    "group": "summer-2026"
  },
  {
    "src": "/gallery/camp/summer-2026/summer-2026-024.webp",
    "thumb": "/gallery/camp/summer-2026/summer-2026-024-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAAAwBACdASoQABwAPu1iqU2ppaOiMAgBMB2JQBWAMX1VIL/7P0JgIkRFKAAA/f9SiDs+5aOeNrgV+eaAak85t3xKQqRyZZrpoUT6tTaFOsdHHpke9xCELB2RGYQZjdLpiigS59ecezO1uWjVeyzof0oOUPgCPUIpqK8mEsABKHxzbOgDqgcA9ALjoxyP0hMrMpRPH1YtkjlhW+oFbgub9upVH3qpECfOzWBj+zAAAAA=",
    "category": "camp",
    "group": "summer-2026"
  },
  {
    "src": "/gallery/camp/summer-2026/summer-2026-025.webp",
    "thumb": "/gallery/camp/summer-2026/summer-2026-025-sm.webp",
    "width": 1800,
    "height": 1013,
    "blur": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAAAQAgCdASoQAAkAA4BaJYgCdAD6eLDZHZmAAP7JZTALz2mJPOzucVGWsZLL7dieu1z2jvca8c7oIIfPWJRAcp25EwyTa+AA",
    "category": "camp",
    "group": "summer-2026"
  },
  {
    "src": "/gallery/camp/summer-2026/summer-2026-026.webp",
    "thumb": "/gallery/camp/summer-2026/summer-2026-026-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAAAwBACdASoQABwAPu1iqk4ppaQiMAgBMB2JQBOgMYTWKEZaszUUnt5tPgAA/rDWAMygNrpDAYb1dVU2pHGyWIrbp6ICZC+70uZ0SB6v9svFopC3M+/FcZIPTW79ZKnaIr9Nr86935wYHNP7Yl68Fqp3hHKmOupYs0GXB6ycd57oTKefIsYSN/8WjtMX/3succkeDlzIa24AFP6g0cHz/ipAUR0NweykAAA=",
    "category": "camp",
    "group": "summer-2026"
  },
  {
    "src": "/gallery/camp/summer-2026/summer-2026-027.webp",
    "thumb": "/gallery/camp/summer-2026/summer-2026-027-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAADQBACdASoQABwAPu1iqU2ppaOiMAgBMB2JYgCdMoAvQTQot2Low3+SS3x29cq/AAD8XIvT+jgssTG0fCj61j2pt+DkQFletaypLDaVdS5JzssBOJTyq3bKCdynNTe58Mt7R6uTykyFWo6ZZDi0WIgURd6r0w+26YCYli1kkINOjng6+Rfcsdr+0KqeZmzI7rrXeuIitbeFi2olN5eLBh1+FYETvpAA",
    "category": "camp",
    "group": "summer-2026"
  },
  {
    "src": "/gallery/camp/summer-2026/summer-2026-028.webp",
    "thumb": "/gallery/camp/summer-2026/summer-2026-028-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRr4AAABXRUJQVlA4ILIAAACQBACdASoQABwAPu1kq04ppaQiMAgBMB2JYgCdAYyy27MVt/NG1YUS5g1SuvgA/oxVugKl3PSb5N/6NJh26jxk6qNlM0ej+g3IeN/9bgCGK4SKTrvng/s861rjCiQ1M7cbW86/Nbz+BItKwGes4bnYZCrj4BobfaiuA6XJLXLNH3Pzeurh2y+qN5raUIR9dL2PVJh9W0Cir0bj9M2DYj3YWlRxGpkleLOuSmr6VC9b34AA",
    "category": "camp",
    "group": "summer-2026"
  },
  {
    "src": "/gallery/camp/summer-2026/summer-2026-029.webp",
    "thumb": "/gallery/camp/summer-2026/summer-2026-029-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAADQBACdASoQABwAPu1iqU2ppaOiMAgBMB2JYwCdBAgR4HveHUYHG83AnMYc6XXjMAD2AVsdCz1I5uq7GL4hH0GD5SxvchDgIz+QDnLXvgTNFvxFsRcY1+CWlGFI4zlxCewMaqpKppe/UMI1by4ZxVihqchWexePfY6XSpg4LWfPgD4gV5ZuvvmkSI2ll3nqCotXrxmhOZL9lRfYAAA=",
    "category": "camp",
    "group": "summer-2026"
  },
  {
    "src": "/gallery/camp/summer-2026/summer-2026-030.webp",
    "thumb": "/gallery/camp/summer-2026/summer-2026-030-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRsoAAABXRUJQVlA4IL4AAADQBACdASoQABwAPu1iqU2ppaOiMAgBMB2JQBOiP/zwAEK6O7MWfb3eIIEVywkeAADifOHKxaO56T4k7UCRp1E89A1PJEk25tJT0HhHMn7zEiOuJcnkR3/vlvHAUDx6yuO0zxTKIKPscYmj4xc/amzkox72iZ/x26BvcVhyIfgnpMBoC8ukSC1cKd8CXvi3hWnnFYU+KaoqVR9Q0uaItqn1yrMHryQo3Vd9P2Oz2Xfp+Ot1MmmdxmRk7knX/2gA",
    "category": "camp",
    "group": "summer-2026"
  },
  {
    "src": "/gallery/camp/summer-2026/summer-2026-031.webp",
    "thumb": "/gallery/camp/summer-2026/summer-2026-031-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRtAAAABXRUJQVlA4IMQAAABQBACdASoQABwAPu1iqU2ppaQiMAgBMB2JZACdMoBOAbUkcoFkI0+cQfQAAP0qUXjQsPxO3D83m0aZu2L5/ac6YpPjLDdekRub3eVK+2wfs95OexB0Ww89tU7iPLm3kodZs7rrEg33X37e8zEkvCZGpEOai79GArENxh49T+0xqnOpwQFUhqcHyUt5WiFSz3+C6YxWLZpRf56jx+BEv85uQsCyPEwpmFYWRSSDTf/FXcB/GTThIZfQ09VuPoHIsp0gAAAA",
    "category": "camp",
    "group": "summer-2026"
  },
  {
    "src": "/gallery/camp/summer-2026/summer-2026-032.webp",
    "thumb": "/gallery/camp/summer-2026/summer-2026-032-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAABwBACdASoQABwAPu1iqU2ppaOiMAgBMB2JagCdMoMh1C3wQPe/Xlt1lGH4gADc+Yxs7hwglNvurpTkySPn9aZ16c662ZurZ0MXOC/A4JZToKymof8vBumUnhUmIT69rxivqZrk/f4sZfu/MdhMzOs4mb5nqeevU6X7JEFwvU3Lwl8FSXn0UhCZmbLPrD/t+VpT7gXlwwlAAA==",
    "category": "camp",
    "group": "summer-2026"
  },
  {
    "src": "/gallery/camp/summer-2026/summer-2026-033.webp",
    "thumb": "/gallery/camp/summer-2026/summer-2026-033-sm.webp",
    "width": 1800,
    "height": 1013,
    "blur": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAwAgCdASoQAAkAA4BaJYgCdAYulnUn66u2AAD+tAjfAH6nm2Nyo1PF/qp/E9qDZtqoyG3q8vOlUhZbS/UQ7zg7hUvOFr76aFUiEeNS9ecAAA==",
    "category": "camp",
    "group": "summer-2026"
  },
  {
    "src": "/gallery/camp/summer-2026/summer-2026-034.webp",
    "thumb": "/gallery/camp/summer-2026/summer-2026-034-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRsIAAABXRUJQVlA4ILYAAABQBACdASoQABwAPu1iqU2ppaOiMAgBMB2JYgCnFYvMpciulS/cRUMbneoAAP7d9B0T6cgX7hjJwsVTbSVVFaSAR/dZOBdJGtDDcHXUbMYlkb/9CKH0AskRq5Iob6QDVX1aEichkhfDNS0giewlhVYNGVtBpZdYwoeMpKdh/MstmxNCyOjer3DmNXNFpfWsboTgT3Nk56AOBMvMu1xXpBiUydI44OzYfFJgh2KJB7rNzgOnkfAAAA==",
    "category": "camp",
    "group": "summer-2026"
  },
  {
    "src": "/gallery/camp/summer-2026/summer-2026-035.webp",
    "thumb": "/gallery/camp/summer-2026/summer-2026-035-sm.webp",
    "width": 1800,
    "height": 1013,
    "blur": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAACwAQCdASoQAAkAA4BaJZQAAWq5D04AAP64CvCOkZopGQfVNKFZOItPw/If8FoMDNzWHz/4OOmOOgXKiPV8Ksq/kJaOoPXyyEFFPIht74AAAA==",
    "category": "camp",
    "group": "summer-2026"
  },
  {
    "src": "/gallery/camp/summer-2026/summer-2026-036.webp",
    "thumb": "/gallery/camp/summer-2026/summer-2026-036-sm.webp",
    "width": 1800,
    "height": 2518,
    "blur": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAACQBACdASoQABYAPu1iqU2ppaQiMAgBMB2JbDuEOAG8iwhD6OrZGQJ/D84viPAA+ryesk3TbtOMToRc36YWZv5X5LXGuGn+cZ9GnevAw5yVKlzQJm3IukAPmVxQHucUc/HtOYq3Sv6fB53EuxPrvqcy/Ksel4BO3MXQdlR7niHDZWnT/W98Up6G9BOk0YOOkjSA8SSfJsSWnPUzGZzmJmb91V0kiekq78hV3JyQAAA=",
    "category": "camp",
    "group": "summer-2026"
  },
  {
    "src": "/gallery/camp/summer-2026/summer-2026-037.webp",
    "thumb": "/gallery/camp/summer-2026/summer-2026-037-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRsIAAABXRUJQVlA4ILYAAACQBACdASoQABwAPu1iqU2ppaOiMAgBMB2JYgCdMoBOAbVs7RL0AiD//rB5rAAA/tXvujmaVQD3wdKit5GWHPtcZ0lXJdy9bn+f3sf9hnjnb+e85gaX+QdlwRqFUudyiuUI9Q0rJX1XqUjcsRoM2Ug8V51o4WWB10/EXTKK3/1lyuEe5pA2OmUb40VibG5wzNn8am6QTeHYicOd+oqD0Os7BLnOt8W7maXu1EYa731f1cr9oAAAAA==",
    "category": "camp",
    "group": "summer-2026"
  },
  {
    "src": "/gallery/camp/summer-2026/summer-2026-038.webp",
    "thumb": "/gallery/camp/summer-2026/summer-2026-038-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRsQAAABXRUJQVlA4ILgAAADQBACdASoQABwAPu1iqk2ppaQiMAgBMB2JYgCdMoAluhZYR64/PWXfOhWjT7gMgAD+s0PexGU0o8HZj55tIyWp9/5qsrP7C/ycadsQoJn6MKLAY4Q6LaFHHGFg8pKTQkPXGoI7sJ+YYhvX/UMNEzZ8rIe8kW66g2dg0qYQjFEYZ5gLrVS/b85dUlA/AZ5DDWS7xp8agf86x60eKpyal3qHGk4WIC1QTrdfzMQ8N1oH0qeO0P0dQAAA",
    "category": "camp",
    "group": "summer-2026"
  },
  {
    "src": "/gallery/camp/summer-2026/summer-2026-039.webp",
    "thumb": "/gallery/camp/summer-2026/summer-2026-039-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAACwAwCdASoQABwAPu1yrU+pp6QiMAgBMB2JagCdAGk6aH4WeDCQwAD+8K3TTBTd4KS+NNNteZnYzNIX7MKzqExZcEIkhUOldl9mNvf91C+33fLeKqitCO2fB+fjVeEMH8SabWWk0Nxnwr5V4ETKHlW+lRi4ZMOsHexTlNUnEJxDNsqx+Gf6R+sFapsowQFxjKt/nsyV+4WhdSilhe7N8s5Wu+GwM9CJvIpSIFjcAAA=",
    "category": "camp",
    "group": "summer-2026"
  },
  {
    "src": "/gallery/camp/summer-2026/summer-2026-040.webp",
    "thumb": "/gallery/camp/summer-2026/summer-2026-040-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRsQAAABXRUJQVlA4ILgAAAAQBACdASoQABwAPu1iqU2ppaQiMAgBMB2JQBOmUABNajBpJZ68p+frAAD8+I4DOmXLCLCerkO1UymPylsd0fnIQibkyHcnrlCgUOKxa1r2KbMXVVe5ichEJ56p0utF9b6MPVwQuTkw1GCh3TzCBj9RClB+i6+fjdDwRBti4yxrNGyCg2p/rxHdTg0lExzEFUnVdutaKtW82Pgjn3wcpGirzhX8jRi+DZ4yzIFoh98yJh9EQSDoMAAA",
    "category": "camp",
    "group": "summer-2026"
  },
  {
    "src": "/gallery/individual/individual-001.webp",
    "thumb": "/gallery/individual/individual-001-sm.webp",
    "width": 1800,
    "height": 3200,
    "blur": "data:image/webp;base64,UklGRsoAAABXRUJQVlA4IL4AAABwBACdASoQABwAPu1iqU2ppaOiMAgBMB2JYgCdMoAlqArQxdBbkKy/y5xgAAD+U+9eQPYOoDhyPZ+ScWcTq/AsixiHinmPPwwfqz3QdoUQTKDh8QpMSlMrBHWoEJtKXVYfC6XA6cxCqzykzdVVFOgRDukf1hwZtLq+pXkUGcgJEXb+6myLlbLBHBDGO/IO0bMM4eFRNVai+JquO4vWtW/LKYcAgtWLeB9uHuncdkH7Yft9Qyyw/aDdJD/wgAAA",
    "category": "individual",
    "group": null
  },
  {
    "src": "/gallery/individual/individual-002.webp",
    "thumb": "/gallery/individual/individual-002-sm.webp",
    "width": 1800,
    "height": 3200,
    "blur": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAABQBACdASoQABwAPu1iqU2ppaOiMAgBMB2JYgCdAYtyZWTDTNdkKMzrPLAAAPxcQ0P7T4UqfFLWCjla//EmFGMoyhlZngFwJkJCT0gzpUya6VUsp5HADUf27qXjt6Q5diaVX/v/XDIgXqJZ6JQxgnc/J6q6Ty3fnYp0Y04uHzvuRTDbRkGS4usgYhyBzfLIYguzfMD3Jo+2zpEG6/Y4clOHerO2mAV1dO7OG1ygAAA=",
    "category": "individual",
    "group": null
  },
  {
    "src": "/gallery/individual/individual-003.webp",
    "thumb": "/gallery/individual/individual-003-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JYwCdAYxilAJOaeLDG1ckJAD3IXPM97vpE84MxR6o41KcBlEA44lkLyLDSdJfol92h/ts86Tewg29wjvgP44BJiEFh+1nWbq3vKvlQx8LCuYD2jAc7ml3zBSnKLgrC5MbbGGrAeLcfS2uqsnIrhIUap1AdyKtyjgAAA==",
    "category": "individual",
    "group": null
  },
  {
    "src": "/gallery/individual/individual-004.webp",
    "thumb": "/gallery/individual/individual-004-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAABwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JQBOmUAXoAxvZgYPEfkdnv4tdAADciJmgn2mZcPNUAp97F7DBmZHG2bqmv+y+dPnXUR3YU5iEMWYF/SCompozGURYu3VJ+ohEBBTDMZtt1dsxt4wUHsJXtd7WyyuZypw97pEPkQRHYEBAIqmLsQaUHgAAAA==",
    "category": "individual",
    "group": null
  },
  {
    "src": "/gallery/individual/individual-005.webp",
    "thumb": "/gallery/individual/individual-005-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAABQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JYgCdINignxZfs/r2pmLHL1JAAPywy9vou/fjsrmyZgJwQk06oz6mYML5jC/KLuyG2X8YKMuRAhpK6hx6d/dmjS5h6S/qX/J2Pz/ljaJxeZ+5vXv53c8XOSB3+j6pSCpSQtteyrrhCk0w4qv3+r773f+8ga2PJ2tuAH0Xwv/KC21R/5sujg4dK5kMG4vsIgAAAA==",
    "category": "individual",
    "group": null
  },
  {
    "src": "/gallery/individual/individual-006.webp",
    "thumb": "/gallery/individual/individual-006-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAABwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JYwCo+3gGy9Q3L3IYOCfmF9/3AAD+xWeJvsPgYqAaf9atT38Dhkg7QACEn0y2g/WmQnsdeb0ahur4E0/bP47O687o8qbGEDp/1wks/+b2LKN1DjoQ7iawX9t2w69erAo7pbCSsxmTPjTYpAe/5qRFeyeJYobZy27Bt/+AAAA=",
    "category": "individual",
    "group": null
  },
  {
    "src": "/gallery/individual/individual-007.webp",
    "thumb": "/gallery/individual/individual-007-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAADQAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JQBWAAuBjfB08YZwv20AA/h1v+Eobf3iOfj6gGz7tvBH8OLf+9aTY5fEImkqfiX+X3KE93iyV035OBR17QMzp64q6i9oNKQgbxamfPo8mtuvfhtrdvp4h1a73P5YONhsCG5dSRJmez3kYEmL2M3kL6pYXbXPjd4u8j0uZs+ZkdGsc8WtAAA==",
    "category": "individual",
    "group": null
  },
  {
    "src": "/gallery/individual/individual-008.webp",
    "thumb": "/gallery/individual/individual-008-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAADQAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JQBOgBFrwhOqF0j0BugAA998czRPSqnw2XcAuNfcSOeCCLeYFt0fhbnfBIlIg2rwKTCUX+VqZNTvP3YQastbakaJsiJ+Ona20DiCggJ4sXSE4CEYoKnX3SBUWwy/G6HbC29Aw/OkvxbiZ2zdiLwBkwMyfmEttuwAAAA==",
    "category": "individual",
    "group": null
  },
  {
    "src": "/gallery/individual/individual-009.webp",
    "thumb": "/gallery/individual/individual-009-sm.webp",
    "width": 1800,
    "height": 1012,
    "blur": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQAgCdASoQAAkAA4BaJZQCdAYuRL1Fo2wAAP5VZzcSclWXDTsL+MU9wVFu1iBgOVUT/wj/cSMqQhAyWqNc2dccafJNJ3ygdyZ0oHVWr9xAAA==",
    "category": "individual",
    "group": null
  },
  {
    "src": "/gallery/individual/individual-010.webp",
    "thumb": "/gallery/individual/individual-010-sm.webp",
    "width": 1800,
    "height": 3200,
    "blur": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAACQBACdASoQABwAPu1iqU2ppaOiMAgBMB2JYwCdMoADTtQ/PMY9vPN5/haRpTAA/dsNoeRdJDBNKlxyolLH0eHEW++TSvmN1ai78H7QLH90SjrH5NZP0qdnc/P3N62lTmf+puUU1W/ZvVGB2+0rvb8bekjwsdiE7hQYZ5SHzV4V1e51Za49d6tfZ9IKf5HIYPumxJP4rodn4BV8YAA=",
    "category": "individual",
    "group": null
  },
  {
    "src": "/gallery/individual/individual-011.webp",
    "thumb": "/gallery/individual/individual-011-sm.webp",
    "width": 1800,
    "height": 3200,
    "blur": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAACQBACdASoQABwAPu1iqU2ppaOiMAgBMB2JYwCdMoAlwBQB7Luu8IYt2pLzrAAA4drXccq0Z96BR3krF3rC0N6anfOQQxdpnxN7yIEwqEVF2S3U16E+p2f37KZPy+5PbhbK0ppRxP8uPl9I+4TFRCC3iNkCugIxb3VXNeOfN6SIR8KnM13SGqcSQxwAAA==",
    "category": "individual",
    "group": null
  },
  {
    "src": "/gallery/individual/individual-012.webp",
    "thumb": "/gallery/individual/individual-012-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAACQBACdASoQABUAPu1iqU2ppaQiMAgBMB2JZACdMoSA2dC4z6gofszizo8DnQAA8CxIHi7FcIv2ZSHynJebqE60U9fdlxLXAWWq2YoDCV+5gMtyOhAGpqC9uen0dkkNSl7BdI+4tQrWQ1JW2mhbuOYzahnprEJytAmFXgih04oroSHbeMAAAA==",
    "category": "individual",
    "group": null
  },
  {
    "src": "/gallery/individual/individual-013.webp",
    "thumb": "/gallery/individual/individual-013-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JQBOgAsbkFDePNrdN75PrgAD+lNRPgmQsJhbJ+GHSet9bGh7W0jYp2iTUZTwEo3t9fxO23Q4/gFJJ9UNASrZP5o1lv0PuvpHB75o4sZ1Ct9b1exXbpAF+cp4RlyokMzfZnj1TznwmycAA",
    "category": "individual",
    "group": null
  },
  {
    "src": "/gallery/individual/individual-014.webp",
    "thumb": "/gallery/individual/individual-014-sm.webp",
    "width": 1800,
    "height": 3200,
    "blur": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAABQBACdASoQABwAPu1kqk4ppaQiMAgBMB2JYgCdAdwA1S7LyAEuRv+LgzMwAPyJWiomOufi4kujKy/1cxMgxuuHWrlnWnLq5vDzYbl0MlIDGFrbdvrh+2kUce/QzvHO2iZy2pHdQq5bE5QG4xiq9N02pXMKSBqg8cdu9ZdE3URPVT25NMPSWjNBv94ngFLqOvAwnVvsGlXR+3CcR094gAAA",
    "category": "individual",
    "group": null
  },
  {
    "src": "/gallery/individual/individual-015.webp",
    "thumb": "/gallery/individual/individual-015-sm.webp",
    "width": 1800,
    "height": 3200,
    "blur": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAAAwBACdASoQABwAPu1kqk4ppaQiMAgBMB2JQBadA6SZtLuLSESHb+72ZQAA/tq6N+73keIRDVMbQydU3JoShmKHXKrjl9Cvzwieh3vJup9YoLnYPzkAaTZpGdN5+Wc7SAWzguPIbb0u7uvdV3PGlplKL3MI+k2nqaWObYzrKT9EYa+AAAA=",
    "category": "individual",
    "group": null
  },
  {
    "src": "/gallery/individual/individual-016.webp",
    "thumb": "/gallery/individual/individual-016-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAACwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JQBOgAgMmJnAx5LUgAAD+ZDrdx9uY7oCn47ch4vyYNVUil6kDHSRICtnOtAPfo3n6cKp08JbwbUe9pts4uuYmwF37NDOpaFeFweiXnmNFYhH321zuiMqDTNLn3V4e2dvB3uj7VdXKMd7ytgAAAA==",
    "category": "individual",
    "group": null
  },
  {
    "src": "/gallery/individual/individual-017.webp",
    "thumb": "/gallery/individual/individual-017-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAACQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JYwC7Ef/i15nbtFN8lbDNoSJ4dyAA/Nlg4I9GdjGXDyg35Xv3dPRzXy9cdNP6qzvaORkUX83Ts8ohQOaW+Ta36+AjsFMOrGEJKwvlapxcQ96xXrBtguM1aqrt65YrDw1EUjvUYx9EPlqfMVBO0nUhx6uMEBbtC/+7mhpPXwDtpo4B0wrOgsUhE5wxoAAA",
    "category": "individual",
    "group": null
  },
  {
    "src": "/gallery/workshops/kids/kids-001.webp",
    "thumb": "/gallery/workshops/kids/kids-001-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAADwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JYgCxG1yA048B81y8/lGAAMtNu+Ke1C8vEY29uJQsBpaJrtjO8j64meCfAiUSpG4SBC5YVbHRyP7PEOkXvyTCMwn8wLVJLqjMyIbLrhuXHI0e7ksiLIY7ADy0cEiYbLldsQbCda8fetAA8dbDatlbbk9sQJOItwAAAA==",
    "category": "workshops",
    "group": "kids"
  },
  {
    "src": "/gallery/workshops/kids/kids-002.webp",
    "thumb": "/gallery/workshops/kids/kids-002-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAABwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JQBOmUABtIvRsjy/0WhmWPdM4AAD+lJKCTubS4S87aAvkYXyvOCCvO01eOJiueTTejYeQ8rtvi6m0yOQBNOIR5eJc+OQ3VefOUga+v9CKsCQGc+g2Ec1oE9X9q5gaNCuzQ2K0TeRr4AAA",
    "category": "workshops",
    "group": "kids"
  },
  {
    "src": "/gallery/workshops/kids/kids-003.webp",
    "thumb": "/gallery/workshops/kids/kids-003-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAABwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JagCdMoRwABJxKfqwXWSjb4ArAAD+5+kBY3CIfudF3GTXW+FTlc3SxOzv9dknmgifWsNuLYyhh55U/xZKAA1f9DUnos6SMY32LDCfsecv79XYSrj3CuRl78eQtaV238XPopLDr0kwDTamrVKw90HT/RQfW0BJPeAgQAAA",
    "category": "workshops",
    "group": "kids"
  },
  {
    "src": "/gallery/workshops/kids/kids-004.webp",
    "thumb": "/gallery/workshops/kids/kids-004-sm.webp",
    "width": 720,
    "height": 1280,
    "blur": "data:image/webp;base64,UklGRsYAAABXRUJQVlA4ILoAAACwBACdASoQABwAPu1iqU2ppaOiMAgBMB2JagCdL1AVhs1PubqMtgef4+z6OdQAAPKKh2o+ms5Uc/ROumXTK6T/3XulrS3eJ0bALmHNQXpT7jIpwmt18tyU7acNbXVpaTkmdYRRR6BbiinCbXrmgbvnHKIB0sug2FmQ95XhoIAR9xXGrW/dzudV8xMke7IB7prma/1wgPmGfCsOdA63Nq/lmoi71sjQ8x53ow4osyqjRIGEX/Hi4TgAAAA=",
    "category": "workshops",
    "group": "kids"
  },
  {
    "src": "/gallery/workshops/kids/kids-005.webp",
    "thumb": "/gallery/workshops/kids/kids-005-sm.webp",
    "width": 960,
    "height": 1280,
    "blur": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAADQAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JaACdIDZBrD3htOLo3gAA/PVD5Gh+cevDP5v6fp8M0ESJKnEADjjZ27C7rduU7nhZkozMAGH8mKLzfXuwirp7jz4aEJJY7V3Xn95u50smaz+G/o/9uGwFcsDi/bX6HGCiAk8oq3x4Hhr4guJI97So+FWPKWX2ehqnteQV+zfIA53HAAA=",
    "category": "workshops",
    "group": "kids"
  },
  {
    "src": "/gallery/workshops/kids/kids-006.webp",
    "thumb": "/gallery/workshops/kids/kids-006-sm.webp",
    "width": 816,
    "height": 1280,
    "blur": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAABQBACdASoQABkAPu1iqU2ppaOiMAgBMB2JQBdgA6Ta2EulHvZFF/gOC8JAAP6vxWTLELKlJrP/474H62mbwnr7j6P9BH22SN5g6DdARUu0w6xJ9SpKy7GBRht1VgzkdXLsEs0y/fC15C5gLjXl/rQSz17jb+p1ToNc/s349SAWoxc+DZerJQoq4VRw0Z1eUrPTMAAA",
    "category": "workshops",
    "group": "kids"
  },
  {
    "src": "/gallery/workshops/kids/kids-007.webp",
    "thumb": "/gallery/workshops/kids/kids-007-sm.webp",
    "width": 875,
    "height": 1280,
    "blur": "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAADQBACdASoQABcAPu1iqU2ppaOiMAgBMB2JYgCw7ywTmYvLhxdsVj+z1p1HUd6pLAD+fqJjzZgt9nQEYNemRK/COY1hSMVxc0cknopzWQed4tK8otAGnUuO2KGXBxL2y5B2INpgwtK26CfqRvJwVXsHng9vWy2/BOo4WkFo4rz5bEUscbq9qI2Pu7X7c8rKArGY2hHae0bIn8as9goPDxPp9D3v3mws0uzwAA==",
    "category": "workshops",
    "group": "kids"
  },
  {
    "src": "/gallery/workshops/kids/kids-008.webp",
    "thumb": "/gallery/workshops/kids/kids-008-sm.webp",
    "width": 960,
    "height": 1280,
    "blur": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAABQAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JQBadAeZ2FUQtHAD+5z8bwft5Vy28kTMjT4M3+6dndT2KUA3uwvnG+Wz8VrhCxHnxQlZcgQLtVk2KpWchICpevjvn/7awNU5ax6Uv8huI0JctV7H7qXEfqqN7mgAA",
    "category": "workshops",
    "group": "kids"
  },
  {
    "src": "/gallery/workshops/kids/kids-009.webp",
    "thumb": "/gallery/workshops/kids/kids-009-sm.webp",
    "width": 960,
    "height": 1280,
    "blur": "data:image/webp;base64,UklGRsQAAABXRUJQVlA4ILgAAACQBQCdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdMoMYLIByAGsZ7yy+AM9AKF1acY2MrQyIQAD9OejhHz/qhA+be2vcX6UKKijZ9tEkS4QAjL6v+fTfrWsMHGSdkKzm3PAbcc5+lUBTizMBpatKbTG5UixA+Ed34/qfXjN8re/4FynW6Yl9FhU3L0CyN5tQjJTv9mVLyIVOb4+5aqCLrnREfv+ed5e9sJt3u4Sz3i0NqlomugvAAAAA",
    "category": "workshops",
    "group": "kids"
  },
  {
    "src": "/gallery/workshops/kids/kids-010.webp",
    "thumb": "/gallery/workshops/kids/kids-010-sm.webp",
    "width": 721,
    "height": 1280,
    "blur": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAACQBACdASoQABwAPu1iqU2ppaOiMAgBMB2JZACdAYxYiNY38adCcDkACllyrAAA/mR2lsbFvSGcOtyu7iwWjKv8ihqkyqqBwyPuMtp7pZ306eAUn5y3UpH9izOyTUwJB6S2880rAW3k9Gvc4a6qhGFar64vlDxSs2VWRKd9FpPtD5BGID7vojR9r2+eG0ZMMmA7n81YblJbNkngxy+IyVsAAAA=",
    "category": "workshops",
    "group": "kids"
  },
  {
    "src": "/gallery/workshops/kids/kids-011.webp",
    "thumb": "/gallery/workshops/kids/kids-011-sm.webp",
    "width": 1800,
    "height": 3200,
    "blur": "data:image/webp;base64,UklGRuoAAABXRUJQVlA4IN4AAACQBACdASoQABwAPu1iqU2ppaOiMAgBMB2JYgAu9UWto3hMilG/PuLaSrHg9AAA9zNxTdsy+OO0qdPIuAw0SobT7L9stvZpwqU71zWOV7B07LJokvKjaEsBOI6vUhXI34IEQgT/5s1Uxyoeumm9tOwErJ3/gLn8bz8ktm4w70KgPnnl3Azg0LwW82d+TIxBtBK/B1XVw/+VUWst7LfR7NiUr6YYfETexqu040egzvp1o1Wo6UNtVJm9WkibuAcH96ZVdQVtxDmDTsSBXU57anRTqMnVQ1yCkH3JB9wAAAA=",
    "category": "workshops",
    "group": "kids"
  },
  {
    "src": "/gallery/workshops/kids/kids-012.webp",
    "thumb": "/gallery/workshops/kids/kids-012-sm.webp",
    "width": 1800,
    "height": 3200,
    "blur": "data:image/webp;base64,UklGRuYAAABXRUJQVlA4INoAAADQBACdASoQABwAPu1iqU2ppaQiMAgBMB2JZACdMoAlwxGd8/fHtu4MGdMSYeZOAAD+o38eXCdiu1DmLt+VG3+t4lubrdFeponrMbg44LRsovols9gSP/33Nzsa0jNByus3qlcHU72E0P1KaJdeiH4fvFqmm8eJfC9XvSDqC7gKbzEHDwcelQdAQGKjJUvb23QShn9TIHnQoRXks++MpFK3dmMyls/a98HSb8O8aHhcaPq+e/u2p/zQAdYOYCemwvnGPobGjQVSonLsY3WiPHMnyNss3XneSsAAAA==",
    "category": "workshops",
    "group": "kids"
  },
  {
    "src": "/gallery/workshops/kids/kids-013.webp",
    "thumb": "/gallery/workshops/kids/kids-013-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JYgCdAywBfCoIdrCHgwQbAAD9pVoJUnKJeB5IAZ7nXEgszdwNtaD4FfWZvxFjRnPXTuswxYqJMgmb0GMmA+HRXzb5DO/ReM5CkizsXs/jRD/99rfOoPKMXFOVc5eTFz0QdDdQ3n23vvuB84L9HAqgAAA=",
    "category": "workshops",
    "group": "kids"
  },
  {
    "src": "/gallery/workshops/kids/kids-014.webp",
    "thumb": "/gallery/workshops/kids/kids-014-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAABQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZAC7IIjDCIutd1f7IGvyha7sAP6fk6kpzElGw7jhdeIXPX5iWmHYWPy3KpPUDYJ0khJ0JrAVSGpOxKDzJ+vF+gh9w6hvchEqfinr/1EraiQONuz2KvP7N7j6JfzDaV9t9pqqbugvg7AsJtrqZn9zuYd4AAAA",
    "category": "workshops",
    "group": "kids"
  },
  {
    "src": "/gallery/workshops/kids/kids-015.webp",
    "thumb": "/gallery/workshops/kids/kids-015-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAACQAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JQBdgA4R4q6VjMCgAAPzcOvVJvovD5YUVhwWw8UpOUrxppzGxYRHEK4WoCfzDoZtqSELnaPwAxXspS9zcyQp02KoEczk+iKJNeoDxJzQndyTAPSjwGPufF5dKrDW+hNjGtY/y3F3ydqKiurIpWYveMA/eX06l1U6DAgAA",
    "category": "workshops",
    "group": "kids"
  },
  {
    "src": "/gallery/workshops/kids/kids-016.webp",
    "thumb": "/gallery/workshops/kids/kids-016-sm.webp",
    "width": 1800,
    "height": 3200,
    "blur": "data:image/webp;base64,UklGRr4AAABXRUJQVlA4ILIAAACQBACdASoQABwAPu1iqU2ppaOiMAgBMB2JQBOgMZeZTLFx2E4ZTZfeQwUKaAAA/dWOxSYbgheZgJTzu0npn55BjDngetgOkc/PvEz7bH5gIV8c6/FzijQjZeMDkbrj6PpKT/SwY3s4hHeT+JnGLssj583pBwa0dmszVfrXiSxhEvfDLObiF45kWH/Nml6zG9rueeqfkWUUvdXMFN8GbfAUkjy9KLTEHaA6L19bj71HAAAA",
    "category": "workshops",
    "group": "kids"
  },
  {
    "src": "/gallery/workshops/kids/kids-017.webp",
    "thumb": "/gallery/workshops/kids/kids-017-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAADwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JQBOgAh//q9okr0o5EU8AAP4IOiMpe4KpHgfCGRJpwetf5WHNdqpVzb2fHABtkNyxH5ECtNUhCcnsRUYbXAW5f5nRQHSQmP814AnStPwdzLUFE3EFeubxhWLqdOui7DJIkvPXUBTiUzqbsqLMb9QAAAA=",
    "category": "workshops",
    "group": "kids"
  },
  {
    "src": "/gallery/workshops/kids/kids-018.webp",
    "thumb": "/gallery/workshops/kids/kids-018-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAACwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JagCdMoBOAbSg21cMe3lYm5XINAOAAP7HabWspdNls5FCoN8ksVSypQRbplBNKE6HBQyXGioJcZd7eVrro8Rz6nBizbYJF0X3GSXnEnQlOLhYQVtYnM/BjOdqeq/vQLCnRb3QeEPvpDYg6/PlYoI223BmaEpo8QcTcndZyPHacPCQc23P/4PH4AazZR5shVwAAA==",
    "category": "workshops",
    "group": "kids"
  },
  {
    "src": "/gallery/workshops/kids/kids-019.webp",
    "thumb": "/gallery/workshops/kids/kids-019-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JaACdMoADKPu+xH5/aD96AAD9K+yhSXrHyBB4lXw/jAxYiF6sN0ABJVDHNPmRZNJx3uEukXy9gKrjLhTuTrCoxRmgszEBuJOdFYgru93axcEklJzCKEIIy2QWlhsrbpAAz/hX3+NyquiJZh9RJivSvb2Z+VIM2K5YPMGziSwAAA==",
    "category": "workshops",
    "group": "kids"
  },
  {
    "src": "/gallery/workshops/kids/kids-020.webp",
    "thumb": "/gallery/workshops/kids/kids-020-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdB3gGy6M/gqyc18/8YAD+jCJyGFTWyoKPYt/HTd8Z0asa6uSCRLbXl1LLfqJwGP/3RWbbUMarQVBcm1ark53FUCcWcnrw0Ar039UbyR7BRNL0boutpWNcUaMYm3BOQvLvaeDO7z4uen6fbTqgivWXz3jO8Id2vLTrg/RT8X2x5jX4NZakAAA=",
    "category": "workshops",
    "group": "kids"
  },
  {
    "src": "/gallery/workshops/kids/kids-021.webp",
    "thumb": "/gallery/workshops/kids/kids-021-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAACwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JYgCsBagSAAxQjk9QWUHZLqCASTAAAP7I1otsFkZQuieqg1KC4ZS7qSup6Qr17osVFqo3kfDfeTtDLFHrWYkg0WtCFoSmIkIJiZN4A4IUHwKBp+CxvVBlbxwQFF94exHXXiibnGHnTiA3gdVLAXpSOcOhuqcZkEIQPUGYWkK2HorPOVOMTJmx6CtvyhH5NXZ8Zg2IWAA=",
    "category": "workshops",
    "group": "kids"
  },
  {
    "src": "/gallery/workshops/kids/kids-022.webp",
    "thumb": "/gallery/workshops/kids/kids-022-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRsIAAABXRUJQVlA4ILYAAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdMoRwAdDc5JXZ+y+zLMAA3/OshO0B43cJa0qBubQljpqxjoidnnz2Hm5fupKwdtyx91O26+jWyZe0N8Zxq9ORnorPw5MyyzuSCLN/6Bm5rpzOVcK/rB4fB2lTDOvuJ9hU9pH0bucOxvKK5gETDT2kfBS6dSQwSf+ZPJ94FghF2K7X+QvglL85ELKd9/IhpUr8XeWSaLs77WKAAA==",
    "category": "workshops",
    "group": "kids"
  },
  {
    "src": "/gallery/workshops/kids/kids-023.webp",
    "thumb": "/gallery/workshops/kids/kids-023-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAACQAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JQBadAbMS0QXv6yYAAP7Xa6iT092yBdI3sPxNQhYqltUvIkYb0j6Qczg5Zz/yNFT7UuTwv0i+WqSs2AnihgBHm3JasIpZ0ex9NBAAAAA=",
    "category": "workshops",
    "group": "kids"
  },
  {
    "src": "/gallery/workshops/kids/kids-024.webp",
    "thumb": "/gallery/workshops/kids/kids-024-sm.webp",
    "width": 1800,
    "height": 2400,
    "blur": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JQBYdhCtB6rcpHANJ0R/44AD+ZlausLKvusKcVH5jI3p8zS59Rk0Y5Cn39BNWSzLk1KiNuBUSN+Q+k55cRdyFRg/MpbMdGLlcAUilcbZ+Ril9vMBdy6+9BCGOkyVcFey16WnbZv4kYwE4tvm4n8BGyRitUAAA",
    "category": "workshops",
    "group": "kids"
  },
  {
    "src": "/gallery/workshops/kids/kids-025.webp",
    "thumb": "/gallery/workshops/kids/kids-025-sm.webp",
    "width": 960,
    "height": 1280,
    "blur": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAACwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JQBOmUAS3onPVUvST2fumIhvX08wAAP3RP63P1NPutyRioxTJjf11V88cGYCkN3SvYYXCqo3qNmXiSzctq1vqmIk0+A20Z/LIW3OfPtzBqL6Ve/OMnichMQc2mQHsDoUfP0XPb6dV/Kat/nWE7B58CBCqgok8ZBN1hnYawAA=",
    "category": "workshops",
    "group": "kids"
  },
  {
    "src": "/gallery/workshops/kids/kids-026.webp",
    "thumb": "/gallery/workshops/kids/kids-026-sm.webp",
    "width": 721,
    "height": 1280,
    "blur": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAADwAwCdASoQABwAPu1iqU2ppaOiMAgBMB2JYgCdAYwwroxdO96KnlAAAPyF/rx8p1DXNZLlU0JiyHALtVecUEme6Zneu0A0vbLavJmGSIoTh25btQd6NTmsu/mVn7jhwZRE2zjSOC+4z5wcVrlAx2DnrzLXLMK/od4U9kOpOouymeMrbX+hY8p8ihRCDEknnH2fgGmRsKsr7XKwpNNUFQU+AAA=",
    "category": "workshops",
    "group": "kids"
  },
  {
    "src": "/gallery/workshops/adults/adults-001.webp",
    "thumb": "/gallery/workshops/adults/adults-001-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRsoAAABXRUJQVlA4IL4AAAAQBQCdASoQABwAPu1iqU2ppaOiMAgBMB2JYgCdMoMYNcAIHgYujbx61mSnWxCL8DAAAPXdJzng0Zn/WzxatFfzVFss/CIuSgSwg+ZhwD5p/VUy/70JBGtDq+hFBIK7XTA9MTbQCy0InQsFghNenyFRVYlb4Cv8tYpU4993rL5dHWzlqTN7+UUk3MdlhGukFjO7+o2c5HLAw5Z180WCVuyI/+0XLw8ff5YJQHH8qjyTR3vPq68SyK/jgzuMQAAA",
    "category": "workshops",
    "group": "adults"
  },
  {
    "src": "/gallery/workshops/adults/adults-002.webp",
    "thumb": "/gallery/workshops/adults/adults-002-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRsgAAABXRUJQVlA4ILwAAACQBACdASoQABwAPu1orU2ppqSiMAgBMB2JQBOgMYUWqEN5a6WIOJc+NpMScAAA/vN/uKh1O2a0e3HPe2le4JCGP6W/4KW+u/bVb3gzhZy3Tq+xGCgfvCiCu3fGbUYNqAlpdie3++T76kH9rWO9Vz/A8JaXQ3z5okuaG4+/MoC1djsfXb3XEdae5AGjOEepcTKplZ3Y1HWkB29Uu/MJ83A02jEPHsK+oWarJJDgVudq9hJVU6ySyNIAnrgAAA==",
    "category": "workshops",
    "group": "adults"
  },
  {
    "src": "/gallery/workshops/adults/adults-003.webp",
    "thumb": "/gallery/workshops/adults/adults-003-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAAAwBACdASoQABwAPu1iqU2ppaQiMAgBMB2JZACdMoAC2Vb0ZjQTZAYUQAAA/ozn5V7Vnn082OsGXBJgociPyMjXgxmnx0Gp5T/M3wxoLQXp+6FEI9NUsxpG0R9WQZiytLJDsct0OMBgpC+ZNVk0lhuRlatOJ6vAd42r4DocFnvnE4j3JkkmTYszao796DT+osAAAA==",
    "category": "workshops",
    "group": "adults"
  },
  {
    "src": "/gallery/workshops/adults/adults-004.webp",
    "thumb": "/gallery/workshops/adults/adults-004-sm.webp",
    "width": 1800,
    "height": 3197,
    "blur": "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAABwBACdASoQABwAPu1iqU2ppaOiMAgBMB2JaACdAywTm4hVaED6O8Jxw/fwAAD9m8InoWl5htFD8F0mw3Np1fTa6wAccQTnpfZ26kOkmIivr7KSa2uf8dJVqPGnWIukJktgLGECWRLRziaMvEsyUSWftRewdQLIY67GcB0ak3cLysznZE5eQnGEKWWjxsbFDFdQDNi81+dInqHom2TVjWX0FcC77N2gAAAAAA==",
    "category": "workshops",
    "group": "adults"
  },
  {
    "src": "/gallery/workshops/adults/adults-005.webp",
    "thumb": "/gallery/workshops/adults/adults-005-sm.webp",
    "width": 1080,
    "height": 1920,
    "blur": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAADQAwCdASoQABwAPu1iqU2ppaOiMAgBMB2JQBOgAWqqBWNCbuHPtyAA/SPUZ1Nvj5B4O1Ma+aD+6s6fPADsW6dFSuj61g8CnJohnWAC4JBivFwmp+RP/TuSPCud0/3IuzOQmR2JjfLO/L5IQxVZ8V/7CcpIpkTh4/twAA==",
    "category": "workshops",
    "group": "adults"
  },
  {
    "src": "/gallery/workshops/adults/adults-006.webp",
    "thumb": "/gallery/workshops/adults/adults-006-sm.webp",
    "width": 1080,
    "height": 1920,
    "blur": "data:image/webp;base64,UklGRtAAAABXRUJQVlA4IMQAAADQBACdASoQABwAPu1iqU2ppaOiMAgBMB2JYgC7MoBOAhANZodHTdaae9iQ6DyBAAD+voT4nNV98Nk2GGHZulUafn+pMLolKUPr2hGWoB5EaDv4OsExs/hJfb+3II4Uc9JZAdEIEwkcGVHNhRQLC10U5ZYk1FtOM9P8dYnvqUrBz2Dz+gMu1Kcr3cdz6q+njq8cOrBfi/GJo353cwMtuiuXKJNaN2cFlljcziPdRrNXXNL4hfyUCMsAiiZQGLbzoWuSAAAA",
    "category": "workshops",
    "group": "adults"
  }
];
